<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220524172534 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Insert Location Data';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0001','1A0','Κόσοβο','Κόσοβο')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0002','ABW','Αρούμπα','Αρούμπα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0003','AFG','Αφγανιστάν','Ισλαμική Δημοκρατία του Αφγανιστάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0004','AFI','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0005','AGO','Ανγκόλα','Δημοκρατία της Ανγκόλας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0006','AIA','Ανγκουίλα','Ανγκουίλα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0007','ALA','Νήσοι Ώλαντ','Νήσοι Ώλαντ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0008','ALB','Αλβανία','Δημοκρατία της Αλβανίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0009','AND','Ανδόρα','Πριγκιπάτο της Ανδόρας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0010','ANT','Ολλανδικές Αντίλλες','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0011','ARE','Ενωμένα Αραβικά Εμιράτα','Ενωμένα Αραβικά Εμιράτα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0012','ARG','Αργεντινή','Δημοκρατία της Αργεντινής')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0013','ARM','Αρμενία','Δημοκρατία της Αρμενίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0014','ASM','Αμερικανική Σαμόα','Έδαφος της Αμερικανικής Σαμόα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0015','ATA','Ανταρκτική','Ανταρκτική')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0016','ATB','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0017','ATG','Αντίγκουα και Μπαρμπούντα','Αντίγκουα και Μπαρμπούντα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0018','ATN','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0019','AUS','Αυστραλία','Κοινοπολιτεία της Αυστραλίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0020','AUT','Αυστρία','Δημοκρατία της Αυστρίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0021','AZE','Αζερμπαϊτζάν','Δημοκρατία του Αζερμπαϊτζάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0022','BDI','Μπουρούντι','Δημοκρατία του Μπουρούντι')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0023','BEL','Βέλγιο','Βασίλειο του Βελγίου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0024','BEN','Μπενίν','Δημοκρατία του Μπενίν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0025','BES','Μπονέρ, Άγιος Ευστάθιος και Σάμπα','Μπονέρ, Άγιος Ευστάθιος και Σάμπα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0026','BFA','Μπουρκίνα','Μπουρκίνα Φάσο')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0027','BGD','Μπανγκλαντές','Λαϊκή Δημοκρατία του Μπανγκλαντές')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0028','BGR','Βουλγαρία','Δημοκρατία της Βουλγαρίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0029','BHR','Μπαχρέιν','Βασίλειο του Μπαχρέιν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0030','BHS','Μπαχάμες','Κοινοπολιτεία των Μπαχαμών')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0031','BIH','Βοσνία και Ερζεγοβίνη','Βοσνία και Ερζεγοβίνη')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0032','BLM','Άγιος Βαρθολομαίος','Εδαφική οντότητα του Αγίου Βαρθολομαίου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0033','BLR','Λευκορωσία','Δημοκρατία της Λευκορωσίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0034','BLZ','Μπελίζε','Μπελίζε')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0035','BMU','Βερμούδες','Βερμούδες')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0036','BOL','Βολιβία','Πολυεθνοτικό Κράτος της Βολιβίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0037','BRA','Βραζιλία','Ομόσπονδη Δημοκρατία της Βραζιλίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0038','BRB','Μπαρμπάντος','Μπαρμπάντος')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0039','BRN','Μπρουνέι','Σουλτανάτο του Μπρουνέι')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0040','BTN','Μπουτάν','Βασίλειο του Μπουτάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0041','BUR','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0042','BVT','Νήσος Μπουβέ','Νήσος Μπουβέ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0043','BWA','Μποτσουάνα','Δημοκρατία της Μποτσουάνας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0044','BYS','Λευκορωσία','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0045','CAF','Κεντροαφρικανική Δημοκρατία','Κεντροαφρικανική Δημοκρατία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0046','CAN','Καναδάς','Καναδάς')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0047','CCK','Νήσοι Κόκος (Κήλινγκ)','Έδαφος των Νήσων Κόκος (Κίλινγκ)')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0048','CHE','Ελβετία','Ελβετική Συνομοσπονδία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0049','CHL','Χιλή','Δημοκρατία της Χιλής')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0050','CHN','Κίνα','Λαϊκή Δημοκρατία της Κίνας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0051','CIV','Ακτή Ελεφαντοστού','Δημοκρατία της Ακτής του Ελεφαντοστού')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0052','CMR','Καμερούν','Δημοκρατία του Καμερούν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0053','COD','Λαϊκή Δημοκρατία του Κονγκό','Λαϊκή Δημοκρατία του Κονγκό')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0054','COG','Κονγκό','Δημοκρατία του Κονγκό')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0055','COK','Νήσοι Κουκ','Νήσοι Κουκ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0056','COL','Κολομβία','Δημοκρατία της Κολομβίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0057','COM','Κομόρες','Ένωση των Κομορών')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0058','CPT','Κλίπερτον','Νήσος Κλίπερτον')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0059','CPV','Πράσινο Ακρωτήριο','Δημοκρατία του Πράσινου Ακρωτηρίου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0060','CRI','Κόστα Ρίκα','Δημοκρατία της Κόστα Ρίκα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0061','CSK','Τσεχοσλοβακία','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0062','CTE','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0063','CUB','Κούβα','Δημοκρατία της Κούβας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0064','CUW','Κουρασάο','Κουρασάο')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0065','CXR','Νήσος των Χριστουγέννων','Έδαφος της Νήσου των Χριστουγέννων')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0066','CYM','Νήσοι Κάιμαν','Έδαφος των Νήσων Καϋμάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0067','CYP','Κύπρος','Κυπριακή Δημοκρατία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0068','CZE','Τσεχία','Τσεχική Δημοκρατία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0069','DDR','Ανατολική Γερμανία','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0070','DEU','Γερμανία','Ομοσπονδιακή Δημοκρατία της Γερμανίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0071','DHY','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0072','DJI','Τζιμπουτί','Δημοκρατία του Τζιμπουτί')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0073','DMA','Ντομίνικα','Κοινοπολιτεία της Ντομίνικα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0074','DNK','Δανία','Βασίλειο της Δανίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0075','DOM','Δομινικανή Δημοκρατία','Δομινικανή Δημοκρατία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0076','DZA','Αλγερία','Λαϊκή Δημοκρατία της Αλγερίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0077','ECU','Ισημερινός','Δημοκρατία του Ισημερινού')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0078','EGY','Αίγυπτος','Αραβική Δημοκρατία της Αιγύπτου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0079','ERI','Ερυθραία','Κράτος της Ερυθραίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0080','ESH','Δυτική Σαχάρα','Δυτική Σαχάρα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0081','ESP','Ισπανία','Βασίλειο της Ισπανίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0082','EST','Εσθονία','Δημοκρατία της Εσθονίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0083','ETH','Αιθιοπία','Ομοσπονδιακή Λαϊκή Δημοκρατία της Αιθιοπίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0084','EUR','Ευρωπαϊκή Ένωση','Ευρωπαϊκή Ένωση')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0085','FIN','Φινλανδία','Δημοκρατία της Φινλανδίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0086','FJI','Φίτζι','Δημοκρατία των Φίτζι')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0087','FLK','Νήσοι Φώκλαντ','Νήσοι Φώκλαντ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0088','FQ0','Γαλλικές περιοχές του νοτίου ημισφαιρίου και της Ανταρκτικής','Γαλλικές περιοχές του νοτίου ημισφαιρίου και της Ανταρκτικής')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0089','FRA','Γαλλία','Γαλλική Δημοκρατία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0090','FRO','Νήσοι Φερόες','Νήσοι Φερόες')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0091','FSM','Μικρονησία','Ηνωμένες Πολιτείες της Μικρονησίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0092','FXX','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0093','GAB','Γκαμπόν','Δημοκρατία της Γκαμπόν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0094','GBR','Ηνωμένο Βασίλειο','Ηνωμένο Βασίλειο της Μεγάλης Βρετανίας και της Βόρειας Ιρλανδίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0095','GEL','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0096','GEO','Γεωργία','Γεωργία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0097','GGY','Γκέρνζι','Βαϊλάτο του Γκέρνζι')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0098','GHA','Γκάνα','Δημοκρατία της Γκάνας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0099','GIB','Γιβραλτάρ','Γιβραλτάρ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0100','GIN','Γουινέα','Δημοκρατία της Γουινέας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0101','GLP','Γουαδελούπη','Γουαδελούπη')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0102','GMB','Γκάμπια','Δημοκρατία της Γκάμπια')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0103','GNB','Γουινέα Μπισάου','Δημοκρατία της Γουινέας Μπισάου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0104','GNQ','Ισημερινή Γουινέα','Δημοκρατία της Ισημερινής Γουινέας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0105','GRC','Ελλάδα','Ελληνική Δημοκρατία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0106','GRD','Γρενάδα','Γρενάδα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0107','GRL','Γροιλανδία','Γροιλανδία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0108','GTM','Γουατεμάλα','Δημοκρατία της Γουατεμάλας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0109','GUF','Γουιάνα','Διαμέρισμα της Γαλλικής Γουιάνας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0110','GUM','Γκουάμ','Έδαφος του Γκουάμ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0111','GUY','Γουιάνα','Συνεργατική Δημοκρατία της Γουιάνας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0112','HKG','Χονγκ Κονγκ','Ειδική Διοικητική Περιοχή Χονγκ Κονγκ της Λαϊκής Δημοκρατίας της Κίνας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0113','HMD','Νήσοι Χερντ και Μακντόναλντ','Έδαφος των Νήσων Χερντ και Μακντόναλντ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0114','HND','Ονδούρα','Δημοκρατία της Ονδούρας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0115','HRV','Κροατία','Δημοκρατία της Κροατίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0116','HTI','Αϊτή','Δημοκρατία της Αϊτής')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0117','HUN','Ουγγαρία','Ουγγαρία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0118','HVO','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0119','IDN','Ινδονησία','Δημοκρατία της Ινδονησίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0120','IMN','Νήσος Μαν','Νήσος Μαν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0121','IND','Ινδία','Δημοκρατία της Ινδίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0122','IOT','Βρετανικό Έδαφος του Ινδικού Ωκεανού','Βρετανικό Έδαφος του Ινδικού Ωκεανού')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0123','IRL','Ιρλανδία','Ιρλανδία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0124','IRN','Ιράν','Ισλαμική Δημοκρατία του Ιράν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0125','IRQ','Ιράκ','Δημοκρατία του Ιράκ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0126','ISL','Ισλανδία','Ισλανδία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0127','ISR','Ισραήλ','Κράτος του Ισραήλ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0128','ITA','Ιταλία','Ιταλική Δημοκρατία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0129','JAM','Τζαμάικα','Τζαμάικα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0130','JEY','Τζέρζι','Bailiwick του Jersey')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0131','JOR','Ιορδανία','Χασεμιτικό Βασίλειο της Ιορδανίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0132','JPN','Ιαπωνία','Ιαπωνία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0133','JTN','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0134','KAZ','Καζαχστάν','Δημοκρατία του Καζαχστάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0135','KEN','Κένυα','Δημοκρατία της Κένυας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0136','KGZ','Κιργιζία','Δημοκρατία της Κιργιζίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0137','KHM','Καμπότζη','Βασίλειο της Καμπότζης')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0138','KIR','Κιριμπάτι','Δημοκρατία του Κιριμπάτι')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0139','KNA','Άγιος Χριστόφορος και Νέβις','Ομοσπονδία Αγίου Χριστοφόρου και Νέβις')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0140','KOR','Νότια Κορέα','Δημοκρατία της Κορέας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0141','KWT','Κουβέιτ','Κράτος του Κουβέιτ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0142','LAO','Λάος','Λαϊκή Δημοκρατία του Λάος')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0143','LBN','Λίβανος','Δημοκρατία του Λιβάνου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0144','LBR','Λιβερία','Δημοκρατία της Λιβερίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0145','LBY','Λιβύη','Κράτος της Λιβύης')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0146','LCA','Αγία Λουκία','Αγία Λουκία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0147','LIE','Λιχτενστάιν','Πριγκηπάτο του Λιχτενστάιν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0148','LKA','Σρι Λάνκα','Λαϊκή Σοσιαλιστική Δημοκρατία της Σρι Λάνκα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0149','LSO','Λεσόθο','Βασίλειο του Λεσόθο')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0150','LTU','Λιθουανία','Δημοκρατία της Λιθουανίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0151','LUX','Λουξεμβούργο','Μεγάλο Δουκάτο του Λουξεμβούργου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0152','LVA','Λετονία','Δημοκρατία της Λετονίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0153','MAC','Μακάο','Ειδική Διοικητική Περιοχή Μακάο της Λαϊκής Δημοκρατίας της Κίνας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0154','MAF','Άγιος Μαρτίνος','Κοινότητα του Αγίου Μαρτίνου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0155','MAR','Μαρόκο','Βασίλειο του Μαρόκου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0156','MCO','Μονακό','Πριγκηπάτο του Μονακό')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0157','MDA','Μολδαβία','Δημοκρατία της Μολδαβίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0158','MDG','Μαδαγασκάρη','Δημοκρατία της Μαδαγασκάρης')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0159','MDV','Μαλδίβες','Δημοκρατία των Μαλδιβών')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0160','MEX','Μεξικό','Ηνωμένες Πολιτείες του Μεξικού')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0161','MHL','Νήσοι Μάρσαλ','Δημοκρατία των Νήσων Μάρσαλ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0162','MID','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0163','MKD','Βόρεια Μακεδονία','Δημοκρατία της Βόρειας Μακεδονίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0164','MLI','Μάλι','Δημοκρατία του Μάλι')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0165','MLT','Μάλτα','Δημοκρατία της Μάλτας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0166','MMR','Μιανμάρ/Βιρμανία','Μιανμάρ/Βιρμανία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0167','MNE','Μαυροβούνιο','Μαυροβούνιο')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0168','MNG','Μογγολία','Μογγολία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0169','MNP','Νήσοι Βόρειες Μαριάνες','Κοινοπολιτεία των Νήσων Βόρειες Μαριάνες')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0170','MOZ','Μοζαμβίκη','Δημοκρατία της Μοζαμβίκης')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0171','MRT','Μαυριτανία','Ισλαμική Δημοκρατία της Μαυριτανίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0172','MSR','Μοντσεράτ','Μοντσεράτ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0173','MTQ','Μαρτινίκα','Διαμέρισμα της Μαρτινίκας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0174','MUS','Μαυρίκιος','Δημοκρατία του Μαυρικίου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0175','MWI','Μαλάουι','Δημοκρατία του Μαλάουι')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0176','MYS','Μαλαισία','Μαλαισία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0177','MYT','Μαγιότ','Μαγιότ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0178','NAM','Ναμίμπια','Δημοκρατία της Ναμίμπιας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0179','NCL','Νέα Καληδονία','Νέα Καληδονία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0180','NER','Νίγηρας','Δημοκρατία του Νίγηρα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0181','NFK','Νήσος Νόρφολκ','Έδαφος της Νήσου Νόρφολκ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0182','NGA','Νιγηρία','Ομοσπονδιακή Δημοκρατία της Νιγηρίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0183','NHB','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0184','NIC','Νικαράγουα','Δημοκρατία της Νικαράγουας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0185','NIU','Νιούε','Δημοκρατία του Νιούε')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0186','NLD','Κάτω Χώρες','Βασίλειο των Κάτω Χωρών')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0187','NOR','Νορβηγία','Βασίλειο της Νορβηγίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0188','NPL','Νεπάλ','Ομοσπονδιακή Λαϊκή Δημοκρατία του Νεπάλ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0189','NRU','Ναουρού','Δημοκρατία του Ναουρού')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0190','NTZ','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0191','NZL','Νέα Ζηλανδία','Νέα Ζηλανδία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0192','OMN','Ομάν','Σουλτανάτο του Ομάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0193','PAK','Πακιστάν','Ισλαμική Δημοκρατία του Πακιστάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0194','PAN','Παναμάς','Δημοκρατία του Παναμά')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0195','PCI','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0196','PCN','Νήσοι Πίτκαιρν','Νήσοι Πίτκαιρν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0197','PCZ','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0198','PER','Περού','Δημοκρατία του Περού')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0199','PHL','Φιλιππίνες','Δημοκρατία των Φιλιππινών')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0200','PLW','Παλάου','Δημοκρατία του Παλάου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0201','PNG','Παπουασία-Νέα Γουινέα','Ανεξάρτητο Κράτος της Παπουασίας-Νέας Γουινέας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0202','POL','Πολωνία','Δημοκρατία της Πολωνίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0203','PRI','Πουέρτο Ρίκο','Κοινοπολιτεία του Πουέρτο Ρίκο')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0204','PRK','Βόρεια Κορέα','Λαοκρατική Δημοκρατία της Κορέας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0205','PRT','Πορτογαλία','Πορτογαλική Δημοκρατία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0206','PRY','Παραγουάη','Δημοκρατία της Παραγουάης')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0207','PSE','Παλαιστίνη','Παλαιστίνη')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0208','PUS','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0209','PYF','Γαλλική Πολυνησία','Έδαφος της Γαλλικής Πολυνησίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0210','QAT','Κατάρ','Κράτος του Κατάρ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0211','REU','Ρεουνιόν','Διαμέρισμα της Ρεουνιόν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0212','RHO','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0213','ROU','Ρουμανία','Ρουμανία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0214','RUS','Ρωσία','Ρωσική Ομοσπονδία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0215','RWA','Ρουάντα','Δημοκρατία της Ρουάντα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0216','SAU','Σαουδική Αραβία','Βασίλειο της Σαουδικής Αραβίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0217','SCG','Σερβία και Μαυροβούνιο','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0218','SDN','Σουδάν','Δημοκρατία του Σουδάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0219','SEN','Σενεγάλη','Δημοκρατία της Σενεγάλης')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0220','SGP','Σιγκαπούρη','Δημοκρατία της Σιγκαπούρης')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0221','SGS','Νήσοι Νότια Γεωργία και Νότιες Σάντουιτς','Νήσοι Νότια Γεωργία και Νότιες Σάντουιτς')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0222','SHN','Αγία Ελένη, Ασενσιόν και Τριστάν ντα Κούνα','Αγία Ελένη, Ασενσιόν και Τριστάν ντα Κούνια')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0223','SJM','Νήσοι Σβάλμπαρντ και Γιαν Μαγιέν','Νήσοι Σβάλμπαρντ και Γιαν Μαγιέν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0224','SKM','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0225','SLB','Νήσοι Σολομώντος','Νήσοι Σολομώντος')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0226','SLE','Σιέρρα Λεόνε','Δημοκρατία της Σιέρρα Λεόνε')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0227','SLV','Ελ Σαλβαδόρ','Δημοκρατία του Ελ Σαλβαδόρ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0228','SMR','Άγιος Μαρίνος','Δημοκρατία του Αγίου Μαρίνου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0229','SOM','Σομαλία','Ομοσπονδιακή Δημοκρατία της Σομαλίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0230','SPM','Σεν Πιέρ και Μικελόν','Εδαφική Κοινότητα Σεν Πιέρ και Μικελόν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0231','SRB','Σερβία','Δημοκρατία της Σερβίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0232','SSD','Νότιο Σουδάν','Δημοκρατία του Νοτίου Σουδάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0233','STP','Σάο Τομέ και Πρίνσιπε','Λαϊκή Δημοκρατία του Σάο Τομέ και Πρίνσιπε')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0234','SUN','Σοβιετική Ένωση','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0235','SUR','Σουρινάμ','Δημοκρατία του Σουρινάμ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0236','SVK','Σλοβακία','Σλοβακική Δημοκρατία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0237','SVN','Σλοβενία','Δημοκρατία της Σλοβενίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0238','SWE','Σουηδία','Βασίλειο της Σουηδίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0239','SWZ','Εσουατίνι','Βασίλειο του Εσουατίνι')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0240','SXM','Άγιος Μαρτίνος','Άγιος Μαρτίνος')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0241','SYC','Σεϋχέλλες','Δημοκρατία των Σεϋχελλών')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0242','SYR','Συρία','Αραβική Δημοκρατία της Συρίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0243','TCA','Νήσοι Τερκ και Κάικος','Νήσοι Τερκ και Κάικος')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0244','TCD','Τσαντ','Δημοκρατία του Τσαντ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0245','TGO','Τόγκο','Δημοκρατία του Τόγκο')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0246','THA','Ταϊλάνδη','Βασίλειο της Ταϊλάνδης')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0247','TJK','Τατζικιστάν','Δημοκρατία του Τατζικιστάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0248','TKL','Τοκελάου','Τοκελάου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0249','TKM','Τουρκμενιστάν','Τουρκμενιστάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0250','TLS','Ανατολικό Τιμόρ','Λαϊκή Δημοκρατία του Ανατολικού Τιμόρ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0251','TMP','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0252','TON','Τόνγκα','Βασίλειο της Τόνγκα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0253','TTO','Τρινιδάδ και Τομπάγκο','Δημοκρατία Τρινιδάδ και Τομπάγκο')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0254','TUN','Τυνησία','Δημοκρατία της Τυνησίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0255','TUR','Τουρκία','Δημοκρατία της Τουρκίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0256','TUV','Τουβαλού','Τουβαλού')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0257','TWN','Ταϊβάν','Ταϊβάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0258','TZA','Τανζανία','Ενωμένη Δημοκρατία της Τανζανίας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0259','UGA','Ουγκάντα','Δημοκρατία της Ουγκάντας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0260','UKR','Ουκρανία','Ουκρανία')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0261','UMI','Απομακρυσμένες Νησίδες των Ηνωμένων Πολιτειών','Απομακρυσμένες Νησίδες των Ηνωμένων Πολιτειών')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0262','URY','Ουρουγουάη','Ανατολική Δημοκρατία της Ουρουγουάης')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0263','USA','Ηνωμένες Πολιτείες','Ηνωμένες Πολιτείες της Αμερικής')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0264','UZB','Ουζμπεκιστάν','Δημοκρατία του Ουζμπεκιστάν')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0265','VAT','Κράτος της Πόλεως του Βατικανού','Αγία Έδρα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0266','VCT','Άγιος Βικέντιος και Γρεναδίνες','Άγιος Βικέντιος και Γρεναδίνες')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0267','VDR','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0268','VEN','Βενεζουέλα','Βολιβαριανή Δημοκρατία της Βενεζουέλας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0269','VGB','Βρετανικές Παρθένοι Νήσοι','Βρετανικές Παρθένοι Νήσοι')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0270','VIR','Αμερικανικές Παρθένοι Νήσοι','Παρθένοι Νήσοι των Ηνωμένων Πολιτειών')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0271','VNM','Βιετνάμ','Σοσιαλιστική Δημοκρατία του Βιετνάμ')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0272','VUT','Βανουάτου','Δημοκρατία του Βανουάτου')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0273','WAK','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0274','WLF','Ουάλις και Φουτούνα','Έδαφος των Νήσων Ουάλις και Φουτούνα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0275','WSM','Σαμόα','Ανεξάρτητο Κράτος της Σαμόα')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0276','YEM','Υεμένη','Δημοκρατία της Υεμένης')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0277','YMD','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0278','YUG','Γιουγκοσλαβία','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0279','ZAF','Νότια Αφρική','Δημοκρατία της Νότιας Αφρικής')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0280','ZMB','Ζάμπια','Δημοκρατία της Ζάμπιας')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0281','ZR0','','')");
        $this->addSql("INSERT INTO  location (code, identifier, name, description)  VALUES('Cvsp0282','ZWE','Ζιμπάμπουε','Δημοκρατία της Ζιμπάμπουε')");


    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
