<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220524165617 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE public_organisation_location (public_organisation_id INTEGER NOT NULL, location_id INTEGER NOT NULL, PRIMARY KEY(public_organisation_id, location_id))');
        $this->addSql('CREATE INDEX IDX_CED76D2BB8D2DE84 ON public_organisation_location (public_organisation_id)');
        $this->addSql('CREATE INDEX IDX_CED76D2B64D218E ON public_organisation_location (location_id)');
        $this->addSql('DROP INDEX IDX_268B9C9D13F556E6');
        $this->addSql('CREATE TEMPORARY TABLE __temp__agent AS SELECT id, has_address_id, name, identifier FROM agent');
        $this->addSql('DROP TABLE agent');
        $this->addSql('CREATE TABLE agent (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, has_address_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, CONSTRAINT FK_268B9C9D13F556E6 FOREIGN KEY (has_address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO agent (id, has_address_id, name, identifier) SELECT id, has_address_id, name, identifier FROM __temp__agent');
        $this->addSql('DROP TABLE __temp__agent');
        $this->addSql('CREATE INDEX IDX_268B9C9D13F556E6 ON agent (has_address_id)');
        $this->addSql('DROP INDEX IDX_A795B5F86ACE3B73');
        $this->addSql('DROP INDEX IDX_A795B5F83414710B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__agent_participation AS SELECT agent_id, participation_id FROM agent_participation');
        $this->addSql('DROP TABLE agent_participation');
        $this->addSql('CREATE TABLE agent_participation (agent_id INTEGER NOT NULL, participation_id INTEGER NOT NULL, PRIMARY KEY(agent_id, participation_id), CONSTRAINT FK_A795B5F83414710B FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_A795B5F86ACE3B73 FOREIGN KEY (participation_id) REFERENCES participation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO agent_participation (agent_id, participation_id) SELECT agent_id, participation_id FROM __temp__agent_participation');
        $this->addSql('DROP TABLE __temp__agent_participation');
        $this->addSql('CREATE INDEX IDX_A795B5F86ACE3B73 ON agent_participation (participation_id)');
        $this->addSql('CREATE INDEX IDX_A795B5F83414710B ON agent_participation (agent_id)');
        $this->addSql('DROP INDEX IDX_A2F98E47FF63FDCB');
        $this->addSql('DROP INDEX IDX_A2F98E47C54C8C93');
        $this->addSql('CREATE TEMPORARY TABLE __temp__channel AS SELECT id, type_id, availability_restriction_id, identifier, opening_hours FROM channel');
        $this->addSql('DROP TABLE channel');
        $this->addSql('CREATE TABLE channel (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type_id INTEGER DEFAULT NULL, availability_restriction_id INTEGER DEFAULT NULL, identifier VARCHAR(255) NOT NULL, opening_hours VARCHAR(255) DEFAULT NULL, CONSTRAINT FK_A2F98E47C54C8C93 FOREIGN KEY (type_id) REFERENCES concept (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_A2F98E47FF63FDCB FOREIGN KEY (availability_restriction_id) REFERENCES opening_hours_specification (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO channel (id, type_id, availability_restriction_id, identifier, opening_hours) SELECT id, type_id, availability_restriction_id, identifier, opening_hours FROM __temp__channel');
        $this->addSql('DROP TABLE __temp__channel');
        $this->addSql('CREATE INDEX IDX_A2F98E47FF63FDCB ON channel (availability_restriction_id)');
        $this->addSql('CREATE INDEX IDX_A2F98E47C54C8C93 ON channel (type_id)');
        $this->addSql('DROP INDEX IDX_91AA94053414710B');
        $this->addSql('DROP INDEX IDX_91AA940572F5A1AA');
        $this->addSql('CREATE TEMPORARY TABLE __temp__channel_agent AS SELECT channel_id, agent_id FROM channel_agent');
        $this->addSql('DROP TABLE channel_agent');
        $this->addSql('CREATE TABLE channel_agent (channel_id INTEGER NOT NULL, agent_id INTEGER NOT NULL, PRIMARY KEY(channel_id, agent_id), CONSTRAINT FK_91AA940572F5A1AA FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_91AA94053414710B FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO channel_agent (channel_id, agent_id) SELECT channel_id, agent_id FROM __temp__channel_agent');
        $this->addSql('DROP TABLE __temp__channel_agent');
        $this->addSql('CREATE INDEX IDX_91AA94053414710B ON channel_agent (agent_id)');
        $this->addSql('CREATE INDEX IDX_91AA940572F5A1AA ON channel_agent (channel_id)');
        $this->addSql('DROP INDEX IDX_7BD124B9B528FC11');
        $this->addSql('DROP INDEX IDX_7BD124B972F5A1AA');
        $this->addSql('CREATE TEMPORARY TABLE __temp__channel_evidence AS SELECT channel_id, evidence_id FROM channel_evidence');
        $this->addSql('DROP TABLE channel_evidence');
        $this->addSql('CREATE TABLE channel_evidence (channel_id INTEGER NOT NULL, evidence_id INTEGER NOT NULL, PRIMARY KEY(channel_id, evidence_id), CONSTRAINT FK_7BD124B972F5A1AA FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_7BD124B9B528FC11 FOREIGN KEY (evidence_id) REFERENCES evidence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO channel_evidence (channel_id, evidence_id) SELECT channel_id, evidence_id FROM __temp__channel_evidence');
        $this->addSql('DROP TABLE __temp__channel_evidence');
        $this->addSql('CREATE INDEX IDX_7BD124B9B528FC11 ON channel_evidence (evidence_id)');
        $this->addSql('CREATE INDEX IDX_7BD124B972F5A1AA ON channel_evidence (channel_id)');
        $this->addSql('DROP INDEX IDX_9B9A7A7AF738CDC');
        $this->addSql('DROP INDEX IDX_9B9A7A75A0D5235');
        $this->addSql('CREATE TEMPORARY TABLE __temp__contact_point_opening_hours_specification AS SELECT contact_point_id, opening_hours_specification_id FROM contact_point_opening_hours_specification');
        $this->addSql('DROP TABLE contact_point_opening_hours_specification');
        $this->addSql('CREATE TABLE contact_point_opening_hours_specification (contact_point_id INTEGER NOT NULL, opening_hours_specification_id INTEGER NOT NULL, PRIMARY KEY(contact_point_id, opening_hours_specification_id), CONSTRAINT FK_9B9A7A75A0D5235 FOREIGN KEY (contact_point_id) REFERENCES contact_point (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_9B9A7A7AF738CDC FOREIGN KEY (opening_hours_specification_id) REFERENCES opening_hours_specification (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO contact_point_opening_hours_specification (contact_point_id, opening_hours_specification_id) SELECT contact_point_id, opening_hours_specification_id FROM __temp__contact_point_opening_hours_specification');
        $this->addSql('DROP TABLE __temp__contact_point_opening_hours_specification');
        $this->addSql('CREATE INDEX IDX_9B9A7A7AF738CDC ON contact_point_opening_hours_specification (opening_hours_specification_id)');
        $this->addSql('CREATE INDEX IDX_9B9A7A75A0D5235 ON contact_point_opening_hours_specification (contact_point_id)');
        $this->addSql('DROP INDEX IDX_182694FC647E6E59');
        $this->addSql('DROP INDEX IDX_182694FC38248176');
        $this->addSql('CREATE TEMPORARY TABLE __temp__cost AS SELECT id, currency_id, if_accessed_through_id, identifier, value, description FROM cost');
        $this->addSql('DROP TABLE cost');
        $this->addSql('CREATE TABLE cost (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, currency_id INTEGER DEFAULT NULL, if_accessed_through_id INTEGER DEFAULT NULL, identifier VARCHAR(255) NOT NULL, value INTEGER DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, CONSTRAINT FK_182694FC38248176 FOREIGN KEY (currency_id) REFERENCES concept (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_182694FC647E6E59 FOREIGN KEY (if_accessed_through_id) REFERENCES channel (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO cost (id, currency_id, if_accessed_through_id, identifier, value, description) SELECT id, currency_id, if_accessed_through_id, identifier, value, description FROM __temp__cost');
        $this->addSql('DROP TABLE __temp__cost');
        $this->addSql('CREATE INDEX IDX_182694FC647E6E59 ON cost (if_accessed_through_id)');
        $this->addSql('CREATE INDEX IDX_182694FC38248176 ON cost (currency_id)');
        $this->addSql('DROP INDEX IDX_8E9D970B8D2DE84');
        $this->addSql('DROP INDEX IDX_8E9D9701DBF857F');
        $this->addSql('CREATE TEMPORARY TABLE __temp__cost_public_organisation AS SELECT cost_id, public_organisation_id FROM cost_public_organisation');
        $this->addSql('DROP TABLE cost_public_organisation');
        $this->addSql('CREATE TABLE cost_public_organisation (cost_id INTEGER NOT NULL, public_organisation_id INTEGER NOT NULL, PRIMARY KEY(cost_id, public_organisation_id), CONSTRAINT FK_8E9D9701DBF857F FOREIGN KEY (cost_id) REFERENCES cost (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_8E9D970B8D2DE84 FOREIGN KEY (public_organisation_id) REFERENCES public_organisation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO cost_public_organisation (cost_id, public_organisation_id) SELECT cost_id, public_organisation_id FROM __temp__cost_public_organisation');
        $this->addSql('DROP TABLE __temp__cost_public_organisation');
        $this->addSql('CREATE INDEX IDX_8E9D970B8D2DE84 ON cost_public_organisation (public_organisation_id)');
        $this->addSql('CREATE INDEX IDX_8E9D9701DBF857F ON cost_public_organisation (cost_id)');
        $this->addSql('DROP INDEX IDX_623A5D80F909284E');
        $this->addSql('DROP INDEX IDX_623A5D80D5F5D3E0');
        $this->addSql('CREATE TEMPORARY TABLE __temp__criterion_requirement_concept AS SELECT criterion_requirement_id, concept_id FROM criterion_requirement_concept');
        $this->addSql('DROP TABLE criterion_requirement_concept');
        $this->addSql('CREATE TABLE criterion_requirement_concept (criterion_requirement_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(criterion_requirement_id, concept_id), CONSTRAINT FK_623A5D80D5F5D3E0 FOREIGN KEY (criterion_requirement_id) REFERENCES criterion_requirement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_623A5D80F909284E FOREIGN KEY (concept_id) REFERENCES concept (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO criterion_requirement_concept (criterion_requirement_id, concept_id) SELECT criterion_requirement_id, concept_id FROM __temp__criterion_requirement_concept');
        $this->addSql('DROP TABLE __temp__criterion_requirement_concept');
        $this->addSql('CREATE INDEX IDX_623A5D80F909284E ON criterion_requirement_concept (concept_id)');
        $this->addSql('CREATE INDEX IDX_623A5D80D5F5D3E0 ON criterion_requirement_concept (criterion_requirement_id)');
        $this->addSql('DROP INDEX IDX_621DC9FFF909284E');
        $this->addSql('DROP INDEX IDX_621DC9FF71F7E88B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__event_concept AS SELECT event_id, concept_id FROM event_concept');
        $this->addSql('DROP TABLE event_concept');
        $this->addSql('CREATE TABLE event_concept (event_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(event_id, concept_id), CONSTRAINT FK_621DC9FF71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_621DC9FFF909284E FOREIGN KEY (concept_id) REFERENCES concept (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO event_concept (event_id, concept_id) SELECT event_id, concept_id FROM __temp__event_concept');
        $this->addSql('DROP TABLE __temp__event_concept');
        $this->addSql('CREATE INDEX IDX_621DC9FFF909284E ON event_concept (concept_id)');
        $this->addSql('CREATE INDEX IDX_621DC9FF71F7E88B ON event_concept (event_id)');
        $this->addSql('DROP INDEX IDX_6507731377CE3D8B');
        $this->addSql('DROP INDEX IDX_6507731371F7E88B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__event_public_service AS SELECT event_id, public_service_id FROM event_public_service');
        $this->addSql('DROP TABLE event_public_service');
        $this->addSql('CREATE TABLE event_public_service (event_id INTEGER NOT NULL, public_service_id INTEGER NOT NULL, PRIMARY KEY(event_id, public_service_id), CONSTRAINT FK_6507731371F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_6507731377CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO event_public_service (event_id, public_service_id) SELECT event_id, public_service_id FROM __temp__event_public_service');
        $this->addSql('DROP TABLE __temp__event_public_service');
        $this->addSql('CREATE INDEX IDX_6507731377CE3D8B ON event_public_service (public_service_id)');
        $this->addSql('CREATE INDEX IDX_6507731371F7E88B ON event_public_service (event_id)');
        $this->addSql('DROP INDEX IDX_C615710C54C8C93');
        $this->addSql('CREATE TEMPORARY TABLE __temp__evidence AS SELECT id, type_id, identifier, name, description FROM evidence');
        $this->addSql('DROP TABLE evidence');
        $this->addSql('CREATE TABLE evidence (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type_id INTEGER DEFAULT NULL, identifier VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, CONSTRAINT FK_C615710C54C8C93 FOREIGN KEY (type_id) REFERENCES concept (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO evidence (id, type_id, identifier, name, description) SELECT id, type_id, identifier, name, description FROM __temp__evidence');
        $this->addSql('DROP TABLE __temp__evidence');
        $this->addSql('CREATE INDEX IDX_C615710C54C8C93 ON evidence (type_id)');
        $this->addSql('DROP INDEX IDX_5F89F092C33F7837');
        $this->addSql('DROP INDEX IDX_5F89F092B528FC11');
        $this->addSql('CREATE TEMPORARY TABLE __temp__evidence_document AS SELECT evidence_id, document_id FROM evidence_document');
        $this->addSql('DROP TABLE evidence_document');
        $this->addSql('CREATE TABLE evidence_document (evidence_id INTEGER NOT NULL, document_id INTEGER NOT NULL, PRIMARY KEY(evidence_id, document_id), CONSTRAINT FK_5F89F092B528FC11 FOREIGN KEY (evidence_id) REFERENCES evidence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_5F89F092C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO evidence_document (evidence_id, document_id) SELECT evidence_id, document_id FROM __temp__evidence_document');
        $this->addSql('DROP TABLE __temp__evidence_document');
        $this->addSql('CREATE INDEX IDX_5F89F092C33F7837 ON evidence_document (document_id)');
        $this->addSql('CREATE INDEX IDX_5F89F092B528FC11 ON evidence_document (evidence_id)');
        $this->addSql('DROP INDEX IDX_5EDEDBC394C75C67');
        $this->addSql('DROP INDEX IDX_5EDEDBC3B528FC11');
        $this->addSql('CREATE TEMPORARY TABLE __temp__evidence_linguistic_system AS SELECT evidence_id, linguistic_system_id FROM evidence_linguistic_system');
        $this->addSql('DROP TABLE evidence_linguistic_system');
        $this->addSql('CREATE TABLE evidence_linguistic_system (evidence_id INTEGER NOT NULL, linguistic_system_id INTEGER NOT NULL, PRIMARY KEY(evidence_id, linguistic_system_id), CONSTRAINT FK_5EDEDBC3B528FC11 FOREIGN KEY (evidence_id) REFERENCES evidence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_5EDEDBC394C75C67 FOREIGN KEY (linguistic_system_id) REFERENCES linguistic_system (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO evidence_linguistic_system (evidence_id, linguistic_system_id) SELECT evidence_id, linguistic_system_id FROM __temp__evidence_linguistic_system');
        $this->addSql('DROP TABLE __temp__evidence_linguistic_system');
        $this->addSql('CREATE INDEX IDX_5EDEDBC394C75C67 ON evidence_linguistic_system (linguistic_system_id)');
        $this->addSql('CREATE INDEX IDX_5EDEDBC3B528FC11 ON evidence_linguistic_system (evidence_id)');
        $this->addSql('DROP INDEX IDX_5E9E89CBB8D2DE84');
        $this->addSql('CREATE TEMPORARY TABLE __temp__location AS SELECT id FROM location');
        $this->addSql('DROP TABLE location');
        $this->addSql('CREATE TABLE location (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, code VARCHAR(255) DEFAULT NULL, identifier VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO location (id) SELECT id FROM __temp__location');
        $this->addSql('DROP TABLE __temp__location');
        $this->addSql('DROP INDEX IDX_3E48E7B6F909284E');
        $this->addSql('DROP INDEX IDX_3E48E7B6DE097880');
        $this->addSql('CREATE TEMPORARY TABLE __temp__output_concept AS SELECT output_id, concept_id FROM output_concept');
        $this->addSql('DROP TABLE output_concept');
        $this->addSql('CREATE TABLE output_concept (output_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(output_id, concept_id), CONSTRAINT FK_3E48E7B6DE097880 FOREIGN KEY (output_id) REFERENCES output (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3E48E7B6F909284E FOREIGN KEY (concept_id) REFERENCES concept (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO output_concept (output_id, concept_id) SELECT output_id, concept_id FROM __temp__output_concept');
        $this->addSql('DROP TABLE __temp__output_concept');
        $this->addSql('CREATE INDEX IDX_3E48E7B6F909284E ON output_concept (concept_id)');
        $this->addSql('CREATE INDEX IDX_3E48E7B6DE097880 ON output_concept (output_id)');
        $this->addSql('DROP INDEX IDX_AC34D191F909284E');
        $this->addSql('DROP INDEX IDX_AC34D1916ACE3B73');
        $this->addSql('CREATE TEMPORARY TABLE __temp__participation_concept AS SELECT participation_id, concept_id FROM participation_concept');
        $this->addSql('DROP TABLE participation_concept');
        $this->addSql('CREATE TABLE participation_concept (participation_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(participation_id, concept_id), CONSTRAINT FK_AC34D1916ACE3B73 FOREIGN KEY (participation_id) REFERENCES participation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_AC34D191F909284E FOREIGN KEY (concept_id) REFERENCES concept (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO participation_concept (participation_id, concept_id) SELECT participation_id, concept_id FROM __temp__participation_concept');
        $this->addSql('DROP TABLE __temp__participation_concept');
        $this->addSql('CREATE INDEX IDX_AC34D191F909284E ON participation_concept (concept_id)');
        $this->addSql('CREATE INDEX IDX_AC34D1916ACE3B73 ON participation_concept (participation_id)');
        $this->addSql('DROP INDEX IDX_BA43C560F853E8FE');
        $this->addSql('DROP INDEX IDX_BA43C5606BF700BD');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service AS SELECT id, status_id, has_competent_authority_id, identifier, name, description, processing_time, keyword FROM public_service');
        $this->addSql('DROP TABLE public_service');
        $this->addSql('CREATE TABLE public_service (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, status_id INTEGER DEFAULT NULL, has_competent_authority_id INTEGER NOT NULL, identifier VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, processing_time VARCHAR(255) DEFAULT NULL --(DC2Type:dateinterval)
        , keyword VARCHAR(255) DEFAULT NULL, CONSTRAINT FK_BA43C5606BF700BD FOREIGN KEY (status_id) REFERENCES concept (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_BA43C560F853E8FE FOREIGN KEY (has_competent_authority_id) REFERENCES public_organisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service (id, status_id, has_competent_authority_id, identifier, name, description, processing_time, keyword) SELECT id, status_id, has_competent_authority_id, identifier, name, description, processing_time, keyword FROM __temp__public_service');
        $this->addSql('DROP TABLE __temp__public_service');
        $this->addSql('CREATE INDEX IDX_BA43C560F853E8FE ON public_service (has_competent_authority_id)');
        $this->addSql('CREATE INDEX IDX_BA43C5606BF700BD ON public_service (status_id)');
        $this->addSql('DROP INDEX IDX_86EAC31DF909284E');
        $this->addSql('DROP INDEX IDX_86EAC31D77CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_concept_sector AS SELECT public_service_id, concept_id FROM public_service_concept_sector');
        $this->addSql('DROP TABLE public_service_concept_sector');
        $this->addSql('CREATE TABLE public_service_concept_sector (public_service_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, concept_id), CONSTRAINT FK_86EAC31D77CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_86EAC31DF909284E FOREIGN KEY (concept_id) REFERENCES concept (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_concept_sector (public_service_id, concept_id) SELECT public_service_id, concept_id FROM __temp__public_service_concept_sector');
        $this->addSql('DROP TABLE __temp__public_service_concept_sector');
        $this->addSql('CREATE INDEX IDX_86EAC31DF909284E ON public_service_concept_sector (concept_id)');
        $this->addSql('CREATE INDEX IDX_86EAC31D77CE3D8B ON public_service_concept_sector (public_service_id)');
        $this->addSql('DROP INDEX IDX_9FE5FD2BF909284E');
        $this->addSql('DROP INDEX IDX_9FE5FD2B77CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_concept_thematicArea AS SELECT public_service_id, concept_id FROM public_service_concept_thematicArea');
        $this->addSql('DROP TABLE public_service_concept_thematicArea');
        $this->addSql('CREATE TABLE public_service_concept_thematicArea (public_service_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, concept_id), CONSTRAINT FK_9FE5FD2B77CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_9FE5FD2BF909284E FOREIGN KEY (concept_id) REFERENCES concept (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_concept_thematicArea (public_service_id, concept_id) SELECT public_service_id, concept_id FROM __temp__public_service_concept_thematicArea');
        $this->addSql('DROP TABLE __temp__public_service_concept_thematicArea');
        $this->addSql('CREATE INDEX IDX_9FE5FD2BF909284E ON public_service_concept_thematicArea (concept_id)');
        $this->addSql('CREATE INDEX IDX_9FE5FD2B77CE3D8B ON public_service_concept_thematicArea (public_service_id)');
        $this->addSql('DROP INDEX IDX_F42D012EF909284E');
        $this->addSql('DROP INDEX IDX_F42D012E77CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_concept_type AS SELECT public_service_id, concept_id FROM public_service_concept_type');
        $this->addSql('DROP TABLE public_service_concept_type');
        $this->addSql('CREATE TABLE public_service_concept_type (public_service_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, concept_id), CONSTRAINT FK_F42D012E77CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_F42D012EF909284E FOREIGN KEY (concept_id) REFERENCES concept (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_concept_type (public_service_id, concept_id) SELECT public_service_id, concept_id FROM __temp__public_service_concept_type');
        $this->addSql('DROP TABLE __temp__public_service_concept_type');
        $this->addSql('CREATE INDEX IDX_F42D012EF909284E ON public_service_concept_type (concept_id)');
        $this->addSql('CREATE INDEX IDX_F42D012E77CE3D8B ON public_service_concept_type (public_service_id)');
        $this->addSql('DROP INDEX IDX_DE12565F94C75C67');
        $this->addSql('DROP INDEX IDX_DE12565F77CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_linguistic_system AS SELECT public_service_id, linguistic_system_id FROM public_service_linguistic_system');
        $this->addSql('DROP TABLE public_service_linguistic_system');
        $this->addSql('CREATE TABLE public_service_linguistic_system (public_service_id INTEGER NOT NULL, linguistic_system_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, linguistic_system_id), CONSTRAINT FK_DE12565F77CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_DE12565F94C75C67 FOREIGN KEY (linguistic_system_id) REFERENCES linguistic_system (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_linguistic_system (public_service_id, linguistic_system_id) SELECT public_service_id, linguistic_system_id FROM __temp__public_service_linguistic_system');
        $this->addSql('DROP TABLE __temp__public_service_linguistic_system');
        $this->addSql('CREATE INDEX IDX_DE12565F94C75C67 ON public_service_linguistic_system (linguistic_system_id)');
        $this->addSql('CREATE INDEX IDX_DE12565F77CE3D8B ON public_service_linguistic_system (public_service_id)');
        $this->addSql('DROP INDEX IDX_D9FF02DF71F7E88B');
        $this->addSql('DROP INDEX IDX_D9FF02DF77CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_event AS SELECT public_service_id, event_id FROM public_service_event');
        $this->addSql('DROP TABLE public_service_event');
        $this->addSql('CREATE TABLE public_service_event (public_service_id INTEGER NOT NULL, event_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, event_id), CONSTRAINT FK_D9FF02DF77CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_D9FF02DF71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_event (public_service_id, event_id) SELECT public_service_id, event_id FROM __temp__public_service_event');
        $this->addSql('DROP TABLE __temp__public_service_event');
        $this->addSql('CREATE INDEX IDX_D9FF02DF71F7E88B ON public_service_event (event_id)');
        $this->addSql('CREATE INDEX IDX_D9FF02DF77CE3D8B ON public_service_event (public_service_id)');
        $this->addSql('DROP INDEX IDX_1738DA48185387FA');
        $this->addSql('DROP INDEX IDX_1738DA481B6D775');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_public_service_requires AS SELECT public_service_source, public_service_target FROM public_service_public_service_requires');
        $this->addSql('DROP TABLE public_service_public_service_requires');
        $this->addSql('CREATE TABLE public_service_public_service_requires (public_service_source INTEGER NOT NULL, public_service_target INTEGER NOT NULL, PRIMARY KEY(public_service_source, public_service_target), CONSTRAINT FK_1738DA481B6D775 FOREIGN KEY (public_service_source) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_1738DA48185387FA FOREIGN KEY (public_service_target) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_public_service_requires (public_service_source, public_service_target) SELECT public_service_source, public_service_target FROM __temp__public_service_public_service_requires');
        $this->addSql('DROP TABLE __temp__public_service_public_service_requires');
        $this->addSql('CREATE INDEX IDX_1738DA48185387FA ON public_service_public_service_requires (public_service_target)');
        $this->addSql('CREATE INDEX IDX_1738DA481B6D775 ON public_service_public_service_requires (public_service_source)');
        $this->addSql('DROP INDEX IDX_A17F6C13185387FA');
        $this->addSql('DROP INDEX IDX_A17F6C131B6D775');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_public_service_related AS SELECT public_service_source, public_service_target FROM public_service_public_service_related');
        $this->addSql('DROP TABLE public_service_public_service_related');
        $this->addSql('CREATE TABLE public_service_public_service_related (public_service_source INTEGER NOT NULL, public_service_target INTEGER NOT NULL, PRIMARY KEY(public_service_source, public_service_target), CONSTRAINT FK_A17F6C131B6D775 FOREIGN KEY (public_service_source) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_A17F6C13185387FA FOREIGN KEY (public_service_target) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_public_service_related (public_service_source, public_service_target) SELECT public_service_source, public_service_target FROM __temp__public_service_public_service_related');
        $this->addSql('DROP TABLE __temp__public_service_public_service_related');
        $this->addSql('CREATE INDEX IDX_A17F6C13185387FA ON public_service_public_service_related (public_service_target)');
        $this->addSql('CREATE INDEX IDX_A17F6C131B6D775 ON public_service_public_service_related (public_service_source)');
        $this->addSql('DROP INDEX IDX_7C775E6D5F5D3E0');
        $this->addSql('DROP INDEX IDX_7C775E677CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_criterion_requirement AS SELECT public_service_id, criterion_requirement_id FROM public_service_criterion_requirement');
        $this->addSql('DROP TABLE public_service_criterion_requirement');
        $this->addSql('CREATE TABLE public_service_criterion_requirement (public_service_id INTEGER NOT NULL, criterion_requirement_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, criterion_requirement_id), CONSTRAINT FK_7C775E677CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_7C775E6D5F5D3E0 FOREIGN KEY (criterion_requirement_id) REFERENCES criterion_requirement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_criterion_requirement (public_service_id, criterion_requirement_id) SELECT public_service_id, criterion_requirement_id FROM __temp__public_service_criterion_requirement');
        $this->addSql('DROP TABLE __temp__public_service_criterion_requirement');
        $this->addSql('CREATE INDEX IDX_7C775E6D5F5D3E0 ON public_service_criterion_requirement (criterion_requirement_id)');
        $this->addSql('CREATE INDEX IDX_7C775E677CE3D8B ON public_service_criterion_requirement (public_service_id)');
        $this->addSql('DROP INDEX IDX_72C969E06ACE3B73');
        $this->addSql('DROP INDEX IDX_72C969E077CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_participation AS SELECT public_service_id, participation_id FROM public_service_participation');
        $this->addSql('DROP TABLE public_service_participation');
        $this->addSql('CREATE TABLE public_service_participation (public_service_id INTEGER NOT NULL, participation_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, participation_id), CONSTRAINT FK_72C969E077CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_72C969E06ACE3B73 FOREIGN KEY (participation_id) REFERENCES participation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_participation (public_service_id, participation_id) SELECT public_service_id, participation_id FROM __temp__public_service_participation');
        $this->addSql('DROP TABLE __temp__public_service_participation');
        $this->addSql('CREATE INDEX IDX_72C969E06ACE3B73 ON public_service_participation (participation_id)');
        $this->addSql('CREATE INDEX IDX_72C969E077CE3D8B ON public_service_participation (public_service_id)');
        $this->addSql('DROP INDEX IDX_82368570B528FC11');
        $this->addSql('DROP INDEX IDX_8236857077CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_evidence AS SELECT public_service_id, evidence_id FROM public_service_evidence');
        $this->addSql('DROP TABLE public_service_evidence');
        $this->addSql('CREATE TABLE public_service_evidence (public_service_id INTEGER NOT NULL, evidence_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, evidence_id), CONSTRAINT FK_8236857077CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_82368570B528FC11 FOREIGN KEY (evidence_id) REFERENCES evidence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_evidence (public_service_id, evidence_id) SELECT public_service_id, evidence_id FROM __temp__public_service_evidence');
        $this->addSql('DROP TABLE __temp__public_service_evidence');
        $this->addSql('CREATE INDEX IDX_82368570B528FC11 ON public_service_evidence (evidence_id)');
        $this->addSql('CREATE INDEX IDX_8236857077CE3D8B ON public_service_evidence (public_service_id)');
        $this->addSql('DROP INDEX IDX_50ECA1259CF430C4');
        $this->addSql('DROP INDEX IDX_50ECA12577CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_legal_resource AS SELECT public_service_id, legal_resource_id FROM public_service_legal_resource');
        $this->addSql('DROP TABLE public_service_legal_resource');
        $this->addSql('CREATE TABLE public_service_legal_resource (public_service_id INTEGER NOT NULL, legal_resource_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, legal_resource_id), CONSTRAINT FK_50ECA12577CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_50ECA1259CF430C4 FOREIGN KEY (legal_resource_id) REFERENCES legal_resource (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_legal_resource (public_service_id, legal_resource_id) SELECT public_service_id, legal_resource_id FROM __temp__public_service_legal_resource');
        $this->addSql('DROP TABLE __temp__public_service_legal_resource');
        $this->addSql('CREATE INDEX IDX_50ECA1259CF430C4 ON public_service_legal_resource (legal_resource_id)');
        $this->addSql('CREATE INDEX IDX_50ECA12577CE3D8B ON public_service_legal_resource (public_service_id)');
        $this->addSql('DROP INDEX IDX_92E2BC98DE097880');
        $this->addSql('DROP INDEX IDX_92E2BC9877CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_output AS SELECT public_service_id, output_id FROM public_service_output');
        $this->addSql('DROP TABLE public_service_output');
        $this->addSql('CREATE TABLE public_service_output (public_service_id INTEGER NOT NULL, output_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, output_id), CONSTRAINT FK_92E2BC9877CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_92E2BC98DE097880 FOREIGN KEY (output_id) REFERENCES output (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_output (public_service_id, output_id) SELECT public_service_id, output_id FROM __temp__public_service_output');
        $this->addSql('DROP TABLE __temp__public_service_output');
        $this->addSql('CREATE INDEX IDX_92E2BC98DE097880 ON public_service_output (output_id)');
        $this->addSql('CREATE INDEX IDX_92E2BC9877CE3D8B ON public_service_output (public_service_id)');
        $this->addSql('DROP INDEX IDX_AFAAC005744E0351');
        $this->addSql('DROP INDEX IDX_AFAAC00577CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_rule AS SELECT public_service_id, rule_id FROM public_service_rule');
        $this->addSql('DROP TABLE public_service_rule');
        $this->addSql('CREATE TABLE public_service_rule (public_service_id INTEGER NOT NULL, rule_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, rule_id), CONSTRAINT FK_AFAAC00577CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_AFAAC005744E0351 FOREIGN KEY (rule_id) REFERENCES rule (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_rule (public_service_id, rule_id) SELECT public_service_id, rule_id FROM __temp__public_service_rule');
        $this->addSql('DROP TABLE __temp__public_service_rule');
        $this->addSql('CREATE INDEX IDX_AFAAC005744E0351 ON public_service_rule (rule_id)');
        $this->addSql('CREATE INDEX IDX_AFAAC00577CE3D8B ON public_service_rule (public_service_id)');
        $this->addSql('DROP INDEX IDX_D0C95BAB64D218E');
        $this->addSql('DROP INDEX IDX_D0C95BAB77CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_location AS SELECT public_service_id, location_id FROM public_service_location');
        $this->addSql('DROP TABLE public_service_location');
        $this->addSql('CREATE TABLE public_service_location (public_service_id INTEGER NOT NULL, location_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, location_id), CONSTRAINT FK_D0C95BAB77CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_D0C95BAB64D218E FOREIGN KEY (location_id) REFERENCES location (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_location (public_service_id, location_id) SELECT public_service_id, location_id FROM __temp__public_service_location');
        $this->addSql('DROP TABLE __temp__public_service_location');
        $this->addSql('CREATE INDEX IDX_D0C95BAB64D218E ON public_service_location (location_id)');
        $this->addSql('CREATE INDEX IDX_D0C95BAB77CE3D8B ON public_service_location (public_service_id)');
        $this->addSql('DROP INDEX IDX_431368845A0D5235');
        $this->addSql('DROP INDEX IDX_4313688477CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_contact_point AS SELECT public_service_id, contact_point_id FROM public_service_contact_point');
        $this->addSql('DROP TABLE public_service_contact_point');
        $this->addSql('CREATE TABLE public_service_contact_point (public_service_id INTEGER NOT NULL, contact_point_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, contact_point_id), CONSTRAINT FK_4313688477CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_431368845A0D5235 FOREIGN KEY (contact_point_id) REFERENCES contact_point (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_contact_point (public_service_id, contact_point_id) SELECT public_service_id, contact_point_id FROM __temp__public_service_contact_point');
        $this->addSql('DROP TABLE __temp__public_service_contact_point');
        $this->addSql('CREATE INDEX IDX_431368845A0D5235 ON public_service_contact_point (contact_point_id)');
        $this->addSql('CREATE INDEX IDX_4313688477CE3D8B ON public_service_contact_point (public_service_id)');
        $this->addSql('DROP INDEX IDX_4BC417DA72F5A1AA');
        $this->addSql('DROP INDEX IDX_4BC417DA77CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_channel AS SELECT public_service_id, channel_id FROM public_service_channel');
        $this->addSql('DROP TABLE public_service_channel');
        $this->addSql('CREATE TABLE public_service_channel (public_service_id INTEGER NOT NULL, channel_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, channel_id), CONSTRAINT FK_4BC417DA77CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_4BC417DA72F5A1AA FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_channel (public_service_id, channel_id) SELECT public_service_id, channel_id FROM __temp__public_service_channel');
        $this->addSql('DROP TABLE __temp__public_service_channel');
        $this->addSql('CREATE INDEX IDX_4BC417DA72F5A1AA ON public_service_channel (channel_id)');
        $this->addSql('CREATE INDEX IDX_4BC417DA77CE3D8B ON public_service_channel (public_service_id)');
        $this->addSql('DROP INDEX IDX_F154F8351DBF857F');
        $this->addSql('DROP INDEX IDX_F154F83577CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_cost AS SELECT public_service_id, cost_id FROM public_service_cost');
        $this->addSql('DROP TABLE public_service_cost');
        $this->addSql('CREATE TABLE public_service_cost (public_service_id INTEGER NOT NULL, cost_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, cost_id), CONSTRAINT FK_F154F83577CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_F154F8351DBF857F FOREIGN KEY (cost_id) REFERENCES cost (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_cost (public_service_id, cost_id) SELECT public_service_id, cost_id FROM __temp__public_service_cost');
        $this->addSql('DROP TABLE __temp__public_service_cost');
        $this->addSql('CREATE INDEX IDX_F154F8351DBF857F ON public_service_cost (cost_id)');
        $this->addSql('CREATE INDEX IDX_F154F83577CE3D8B ON public_service_cost (public_service_id)');
        $this->addSql('DROP INDEX IDX_76885D53D95C7B13');
        $this->addSql('DROP INDEX IDX_76885D5377CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_public_service_dataset AS SELECT public_service_id, public_service_dataset_id FROM public_service_public_service_dataset');
        $this->addSql('DROP TABLE public_service_public_service_dataset');
        $this->addSql('CREATE TABLE public_service_public_service_dataset (public_service_id INTEGER NOT NULL, public_service_dataset_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, public_service_dataset_id), CONSTRAINT FK_76885D5377CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_76885D53D95C7B13 FOREIGN KEY (public_service_dataset_id) REFERENCES public_service_dataset (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_public_service_dataset (public_service_id, public_service_dataset_id) SELECT public_service_id, public_service_dataset_id FROM __temp__public_service_public_service_dataset');
        $this->addSql('DROP TABLE __temp__public_service_public_service_dataset');
        $this->addSql('CREATE INDEX IDX_76885D53D95C7B13 ON public_service_public_service_dataset (public_service_dataset_id)');
        $this->addSql('CREATE INDEX IDX_76885D5377CE3D8B ON public_service_public_service_dataset (public_service_id)');
        $this->addSql('DROP INDEX IDX_8D0FA0C9F909284E');
        $this->addSql('DROP INDEX IDX_8D0FA0C977CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_concept_isClassifiedBy AS SELECT public_service_id, concept_id FROM public_service_concept_isClassifiedBy');
        $this->addSql('DROP TABLE public_service_concept_isClassifiedBy');
        $this->addSql('CREATE TABLE public_service_concept_isClassifiedBy (public_service_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, concept_id), CONSTRAINT FK_8D0FA0C977CE3D8B FOREIGN KEY (public_service_id) REFERENCES public_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_8D0FA0C9F909284E FOREIGN KEY (concept_id) REFERENCES concept (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_concept_isClassifiedBy (public_service_id, concept_id) SELECT public_service_id, concept_id FROM __temp__public_service_concept_isClassifiedBy');
        $this->addSql('DROP TABLE __temp__public_service_concept_isClassifiedBy');
        $this->addSql('CREATE INDEX IDX_8D0FA0C9F909284E ON public_service_concept_isClassifiedBy (concept_id)');
        $this->addSql('CREATE INDEX IDX_8D0FA0C977CE3D8B ON public_service_concept_isClassifiedBy (public_service_id)');
        $this->addSql('DROP INDEX IDX_5E9DD84D40C86FCE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_dataset AS SELECT id, publisher_id, identifier, name FROM public_service_dataset');
        $this->addSql('DROP TABLE public_service_dataset');
        $this->addSql('CREATE TABLE public_service_dataset (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, publisher_id INTEGER NOT NULL, identifier VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, CONSTRAINT FK_5E9DD84D40C86FCE FOREIGN KEY (publisher_id) REFERENCES agent (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_dataset (id, publisher_id, identifier, name) SELECT id, publisher_id, identifier, name FROM __temp__public_service_dataset');
        $this->addSql('DROP TABLE __temp__public_service_dataset');
        $this->addSql('CREATE INDEX IDX_5E9DD84D40C86FCE ON public_service_dataset (publisher_id)');
        $this->addSql('DROP INDEX IDX_B4173894C33F7837');
        $this->addSql('DROP INDEX IDX_B4173894D95C7B13');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_dataset_document AS SELECT public_service_dataset_id, document_id FROM public_service_dataset_document');
        $this->addSql('DROP TABLE public_service_dataset_document');
        $this->addSql('CREATE TABLE public_service_dataset_document (public_service_dataset_id INTEGER NOT NULL, document_id INTEGER NOT NULL, PRIMARY KEY(public_service_dataset_id, document_id), CONSTRAINT FK_B4173894D95C7B13 FOREIGN KEY (public_service_dataset_id) REFERENCES public_service_dataset (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B4173894C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO public_service_dataset_document (public_service_dataset_id, document_id) SELECT public_service_dataset_id, document_id FROM __temp__public_service_dataset_document');
        $this->addSql('DROP TABLE __temp__public_service_dataset_document');
        $this->addSql('CREATE INDEX IDX_B4173894C33F7837 ON public_service_dataset_document (document_id)');
        $this->addSql('CREATE INDEX IDX_B4173894D95C7B13 ON public_service_dataset_document (public_service_dataset_id)');
        $this->addSql('DROP INDEX IDX_CEBAD91394C75C67');
        $this->addSql('DROP INDEX IDX_CEBAD913744E0351');
        $this->addSql('CREATE TEMPORARY TABLE __temp__rule_linguistic_system AS SELECT rule_id, linguistic_system_id FROM rule_linguistic_system');
        $this->addSql('DROP TABLE rule_linguistic_system');
        $this->addSql('CREATE TABLE rule_linguistic_system (rule_id INTEGER NOT NULL, linguistic_system_id INTEGER NOT NULL, PRIMARY KEY(rule_id, linguistic_system_id), CONSTRAINT FK_CEBAD913744E0351 FOREIGN KEY (rule_id) REFERENCES rule (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_CEBAD91394C75C67 FOREIGN KEY (linguistic_system_id) REFERENCES linguistic_system (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO rule_linguistic_system (rule_id, linguistic_system_id) SELECT rule_id, linguistic_system_id FROM __temp__rule_linguistic_system');
        $this->addSql('DROP TABLE __temp__rule_linguistic_system');
        $this->addSql('CREATE INDEX IDX_CEBAD91394C75C67 ON rule_linguistic_system (linguistic_system_id)');
        $this->addSql('CREATE INDEX IDX_CEBAD913744E0351 ON rule_linguistic_system (rule_id)');
        $this->addSql('DROP INDEX IDX_43F329769CF430C4');
        $this->addSql('DROP INDEX IDX_43F32976744E0351');
        $this->addSql('CREATE TEMPORARY TABLE __temp__rule_legal_resource AS SELECT rule_id, legal_resource_id FROM rule_legal_resource');
        $this->addSql('DROP TABLE rule_legal_resource');
        $this->addSql('CREATE TABLE rule_legal_resource (rule_id INTEGER NOT NULL, legal_resource_id INTEGER NOT NULL, PRIMARY KEY(rule_id, legal_resource_id), CONSTRAINT FK_43F32976744E0351 FOREIGN KEY (rule_id) REFERENCES rule (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_43F329769CF430C4 FOREIGN KEY (legal_resource_id) REFERENCES legal_resource (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO rule_legal_resource (rule_id, legal_resource_id) SELECT rule_id, legal_resource_id FROM __temp__rule_legal_resource');
        $this->addSql('DROP TABLE __temp__rule_legal_resource');
        $this->addSql('CREATE INDEX IDX_43F329769CF430C4 ON rule_legal_resource (legal_resource_id)');
        $this->addSql('CREATE INDEX IDX_43F32976744E0351 ON rule_legal_resource (rule_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE public_organisation_location');
        $this->addSql('DROP INDEX IDX_268B9C9D13F556E6');
        $this->addSql('CREATE TEMPORARY TABLE __temp__agent AS SELECT id, has_address_id, name, identifier FROM agent');
        $this->addSql('DROP TABLE agent');
        $this->addSql('CREATE TABLE agent (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, has_address_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO agent (id, has_address_id, name, identifier) SELECT id, has_address_id, name, identifier FROM __temp__agent');
        $this->addSql('DROP TABLE __temp__agent');
        $this->addSql('CREATE INDEX IDX_268B9C9D13F556E6 ON agent (has_address_id)');
        $this->addSql('DROP INDEX IDX_A795B5F83414710B');
        $this->addSql('DROP INDEX IDX_A795B5F86ACE3B73');
        $this->addSql('CREATE TEMPORARY TABLE __temp__agent_participation AS SELECT agent_id, participation_id FROM agent_participation');
        $this->addSql('DROP TABLE agent_participation');
        $this->addSql('CREATE TABLE agent_participation (agent_id INTEGER NOT NULL, participation_id INTEGER NOT NULL, PRIMARY KEY(agent_id, participation_id))');
        $this->addSql('INSERT INTO agent_participation (agent_id, participation_id) SELECT agent_id, participation_id FROM __temp__agent_participation');
        $this->addSql('DROP TABLE __temp__agent_participation');
        $this->addSql('CREATE INDEX IDX_A795B5F83414710B ON agent_participation (agent_id)');
        $this->addSql('CREATE INDEX IDX_A795B5F86ACE3B73 ON agent_participation (participation_id)');
        $this->addSql('DROP INDEX IDX_A2F98E47C54C8C93');
        $this->addSql('DROP INDEX IDX_A2F98E47FF63FDCB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__channel AS SELECT id, type_id, availability_restriction_id, identifier, opening_hours FROM channel');
        $this->addSql('DROP TABLE channel');
        $this->addSql('CREATE TABLE channel (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type_id INTEGER DEFAULT NULL, availability_restriction_id INTEGER DEFAULT NULL, identifier VARCHAR(255) NOT NULL, opening_hours VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO channel (id, type_id, availability_restriction_id, identifier, opening_hours) SELECT id, type_id, availability_restriction_id, identifier, opening_hours FROM __temp__channel');
        $this->addSql('DROP TABLE __temp__channel');
        $this->addSql('CREATE INDEX IDX_A2F98E47C54C8C93 ON channel (type_id)');
        $this->addSql('CREATE INDEX IDX_A2F98E47FF63FDCB ON channel (availability_restriction_id)');
        $this->addSql('DROP INDEX IDX_91AA940572F5A1AA');
        $this->addSql('DROP INDEX IDX_91AA94053414710B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__channel_agent AS SELECT channel_id, agent_id FROM channel_agent');
        $this->addSql('DROP TABLE channel_agent');
        $this->addSql('CREATE TABLE channel_agent (channel_id INTEGER NOT NULL, agent_id INTEGER NOT NULL, PRIMARY KEY(channel_id, agent_id))');
        $this->addSql('INSERT INTO channel_agent (channel_id, agent_id) SELECT channel_id, agent_id FROM __temp__channel_agent');
        $this->addSql('DROP TABLE __temp__channel_agent');
        $this->addSql('CREATE INDEX IDX_91AA940572F5A1AA ON channel_agent (channel_id)');
        $this->addSql('CREATE INDEX IDX_91AA94053414710B ON channel_agent (agent_id)');
        $this->addSql('DROP INDEX IDX_7BD124B972F5A1AA');
        $this->addSql('DROP INDEX IDX_7BD124B9B528FC11');
        $this->addSql('CREATE TEMPORARY TABLE __temp__channel_evidence AS SELECT channel_id, evidence_id FROM channel_evidence');
        $this->addSql('DROP TABLE channel_evidence');
        $this->addSql('CREATE TABLE channel_evidence (channel_id INTEGER NOT NULL, evidence_id INTEGER NOT NULL, PRIMARY KEY(channel_id, evidence_id))');
        $this->addSql('INSERT INTO channel_evidence (channel_id, evidence_id) SELECT channel_id, evidence_id FROM __temp__channel_evidence');
        $this->addSql('DROP TABLE __temp__channel_evidence');
        $this->addSql('CREATE INDEX IDX_7BD124B972F5A1AA ON channel_evidence (channel_id)');
        $this->addSql('CREATE INDEX IDX_7BD124B9B528FC11 ON channel_evidence (evidence_id)');
        $this->addSql('DROP INDEX IDX_9B9A7A75A0D5235');
        $this->addSql('DROP INDEX IDX_9B9A7A7AF738CDC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__contact_point_opening_hours_specification AS SELECT contact_point_id, opening_hours_specification_id FROM contact_point_opening_hours_specification');
        $this->addSql('DROP TABLE contact_point_opening_hours_specification');
        $this->addSql('CREATE TABLE contact_point_opening_hours_specification (contact_point_id INTEGER NOT NULL, opening_hours_specification_id INTEGER NOT NULL, PRIMARY KEY(contact_point_id, opening_hours_specification_id))');
        $this->addSql('INSERT INTO contact_point_opening_hours_specification (contact_point_id, opening_hours_specification_id) SELECT contact_point_id, opening_hours_specification_id FROM __temp__contact_point_opening_hours_specification');
        $this->addSql('DROP TABLE __temp__contact_point_opening_hours_specification');
        $this->addSql('CREATE INDEX IDX_9B9A7A75A0D5235 ON contact_point_opening_hours_specification (contact_point_id)');
        $this->addSql('CREATE INDEX IDX_9B9A7A7AF738CDC ON contact_point_opening_hours_specification (opening_hours_specification_id)');
        $this->addSql('DROP INDEX IDX_182694FC38248176');
        $this->addSql('DROP INDEX IDX_182694FC647E6E59');
        $this->addSql('CREATE TEMPORARY TABLE __temp__cost AS SELECT id, currency_id, if_accessed_through_id, identifier, value, description FROM cost');
        $this->addSql('DROP TABLE cost');
        $this->addSql('CREATE TABLE cost (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, currency_id INTEGER DEFAULT NULL, if_accessed_through_id INTEGER DEFAULT NULL, identifier VARCHAR(255) NOT NULL, value INTEGER DEFAULT NULL, description VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO cost (id, currency_id, if_accessed_through_id, identifier, value, description) SELECT id, currency_id, if_accessed_through_id, identifier, value, description FROM __temp__cost');
        $this->addSql('DROP TABLE __temp__cost');
        $this->addSql('CREATE INDEX IDX_182694FC38248176 ON cost (currency_id)');
        $this->addSql('CREATE INDEX IDX_182694FC647E6E59 ON cost (if_accessed_through_id)');
        $this->addSql('DROP INDEX IDX_8E9D9701DBF857F');
        $this->addSql('DROP INDEX IDX_8E9D970B8D2DE84');
        $this->addSql('CREATE TEMPORARY TABLE __temp__cost_public_organisation AS SELECT cost_id, public_organisation_id FROM cost_public_organisation');
        $this->addSql('DROP TABLE cost_public_organisation');
        $this->addSql('CREATE TABLE cost_public_organisation (cost_id INTEGER NOT NULL, public_organisation_id INTEGER NOT NULL, PRIMARY KEY(cost_id, public_organisation_id))');
        $this->addSql('INSERT INTO cost_public_organisation (cost_id, public_organisation_id) SELECT cost_id, public_organisation_id FROM __temp__cost_public_organisation');
        $this->addSql('DROP TABLE __temp__cost_public_organisation');
        $this->addSql('CREATE INDEX IDX_8E9D9701DBF857F ON cost_public_organisation (cost_id)');
        $this->addSql('CREATE INDEX IDX_8E9D970B8D2DE84 ON cost_public_organisation (public_organisation_id)');
        $this->addSql('DROP INDEX IDX_623A5D80D5F5D3E0');
        $this->addSql('DROP INDEX IDX_623A5D80F909284E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__criterion_requirement_concept AS SELECT criterion_requirement_id, concept_id FROM criterion_requirement_concept');
        $this->addSql('DROP TABLE criterion_requirement_concept');
        $this->addSql('CREATE TABLE criterion_requirement_concept (criterion_requirement_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(criterion_requirement_id, concept_id))');
        $this->addSql('INSERT INTO criterion_requirement_concept (criterion_requirement_id, concept_id) SELECT criterion_requirement_id, concept_id FROM __temp__criterion_requirement_concept');
        $this->addSql('DROP TABLE __temp__criterion_requirement_concept');
        $this->addSql('CREATE INDEX IDX_623A5D80D5F5D3E0 ON criterion_requirement_concept (criterion_requirement_id)');
        $this->addSql('CREATE INDEX IDX_623A5D80F909284E ON criterion_requirement_concept (concept_id)');
        $this->addSql('DROP INDEX IDX_621DC9FF71F7E88B');
        $this->addSql('DROP INDEX IDX_621DC9FFF909284E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__event_concept AS SELECT event_id, concept_id FROM event_concept');
        $this->addSql('DROP TABLE event_concept');
        $this->addSql('CREATE TABLE event_concept (event_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(event_id, concept_id))');
        $this->addSql('INSERT INTO event_concept (event_id, concept_id) SELECT event_id, concept_id FROM __temp__event_concept');
        $this->addSql('DROP TABLE __temp__event_concept');
        $this->addSql('CREATE INDEX IDX_621DC9FF71F7E88B ON event_concept (event_id)');
        $this->addSql('CREATE INDEX IDX_621DC9FFF909284E ON event_concept (concept_id)');
        $this->addSql('DROP INDEX IDX_6507731371F7E88B');
        $this->addSql('DROP INDEX IDX_6507731377CE3D8B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__event_public_service AS SELECT event_id, public_service_id FROM event_public_service');
        $this->addSql('DROP TABLE event_public_service');
        $this->addSql('CREATE TABLE event_public_service (event_id INTEGER NOT NULL, public_service_id INTEGER NOT NULL, PRIMARY KEY(event_id, public_service_id))');
        $this->addSql('INSERT INTO event_public_service (event_id, public_service_id) SELECT event_id, public_service_id FROM __temp__event_public_service');
        $this->addSql('DROP TABLE __temp__event_public_service');
        $this->addSql('CREATE INDEX IDX_6507731371F7E88B ON event_public_service (event_id)');
        $this->addSql('CREATE INDEX IDX_6507731377CE3D8B ON event_public_service (public_service_id)');
        $this->addSql('DROP INDEX IDX_C615710C54C8C93');
        $this->addSql('CREATE TEMPORARY TABLE __temp__evidence AS SELECT id, type_id, identifier, name, description FROM evidence');
        $this->addSql('DROP TABLE evidence');
        $this->addSql('CREATE TABLE evidence (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type_id INTEGER DEFAULT NULL, identifier VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO evidence (id, type_id, identifier, name, description) SELECT id, type_id, identifier, name, description FROM __temp__evidence');
        $this->addSql('DROP TABLE __temp__evidence');
        $this->addSql('CREATE INDEX IDX_C615710C54C8C93 ON evidence (type_id)');
        $this->addSql('DROP INDEX IDX_5F89F092B528FC11');
        $this->addSql('DROP INDEX IDX_5F89F092C33F7837');
        $this->addSql('CREATE TEMPORARY TABLE __temp__evidence_document AS SELECT evidence_id, document_id FROM evidence_document');
        $this->addSql('DROP TABLE evidence_document');
        $this->addSql('CREATE TABLE evidence_document (evidence_id INTEGER NOT NULL, document_id INTEGER NOT NULL, PRIMARY KEY(evidence_id, document_id))');
        $this->addSql('INSERT INTO evidence_document (evidence_id, document_id) SELECT evidence_id, document_id FROM __temp__evidence_document');
        $this->addSql('DROP TABLE __temp__evidence_document');
        $this->addSql('CREATE INDEX IDX_5F89F092B528FC11 ON evidence_document (evidence_id)');
        $this->addSql('CREATE INDEX IDX_5F89F092C33F7837 ON evidence_document (document_id)');
        $this->addSql('DROP INDEX IDX_5EDEDBC3B528FC11');
        $this->addSql('DROP INDEX IDX_5EDEDBC394C75C67');
        $this->addSql('CREATE TEMPORARY TABLE __temp__evidence_linguistic_system AS SELECT evidence_id, linguistic_system_id FROM evidence_linguistic_system');
        $this->addSql('DROP TABLE evidence_linguistic_system');
        $this->addSql('CREATE TABLE evidence_linguistic_system (evidence_id INTEGER NOT NULL, linguistic_system_id INTEGER NOT NULL, PRIMARY KEY(evidence_id, linguistic_system_id))');
        $this->addSql('INSERT INTO evidence_linguistic_system (evidence_id, linguistic_system_id) SELECT evidence_id, linguistic_system_id FROM __temp__evidence_linguistic_system');
        $this->addSql('DROP TABLE __temp__evidence_linguistic_system');
        $this->addSql('CREATE INDEX IDX_5EDEDBC3B528FC11 ON evidence_linguistic_system (evidence_id)');
        $this->addSql('CREATE INDEX IDX_5EDEDBC394C75C67 ON evidence_linguistic_system (linguistic_system_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__location AS SELECT id FROM location');
        $this->addSql('DROP TABLE location');
        $this->addSql('CREATE TABLE location (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, public_organisation_id INTEGER DEFAULT NULL)');
        $this->addSql('INSERT INTO location (id) SELECT id FROM __temp__location');
        $this->addSql('DROP TABLE __temp__location');
        $this->addSql('CREATE INDEX IDX_5E9E89CBB8D2DE84 ON location (public_organisation_id)');
        $this->addSql('DROP INDEX IDX_3E48E7B6DE097880');
        $this->addSql('DROP INDEX IDX_3E48E7B6F909284E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__output_concept AS SELECT output_id, concept_id FROM output_concept');
        $this->addSql('DROP TABLE output_concept');
        $this->addSql('CREATE TABLE output_concept (output_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(output_id, concept_id))');
        $this->addSql('INSERT INTO output_concept (output_id, concept_id) SELECT output_id, concept_id FROM __temp__output_concept');
        $this->addSql('DROP TABLE __temp__output_concept');
        $this->addSql('CREATE INDEX IDX_3E48E7B6DE097880 ON output_concept (output_id)');
        $this->addSql('CREATE INDEX IDX_3E48E7B6F909284E ON output_concept (concept_id)');
        $this->addSql('DROP INDEX IDX_AC34D1916ACE3B73');
        $this->addSql('DROP INDEX IDX_AC34D191F909284E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__participation_concept AS SELECT participation_id, concept_id FROM participation_concept');
        $this->addSql('DROP TABLE participation_concept');
        $this->addSql('CREATE TABLE participation_concept (participation_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(participation_id, concept_id))');
        $this->addSql('INSERT INTO participation_concept (participation_id, concept_id) SELECT participation_id, concept_id FROM __temp__participation_concept');
        $this->addSql('DROP TABLE __temp__participation_concept');
        $this->addSql('CREATE INDEX IDX_AC34D1916ACE3B73 ON participation_concept (participation_id)');
        $this->addSql('CREATE INDEX IDX_AC34D191F909284E ON participation_concept (concept_id)');
        $this->addSql('DROP INDEX IDX_BA43C5606BF700BD');
        $this->addSql('DROP INDEX IDX_BA43C560F853E8FE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service AS SELECT id, status_id, has_competent_authority_id, identifier, name, description, processing_time, keyword FROM public_service');
        $this->addSql('DROP TABLE public_service');
        $this->addSql('CREATE TABLE public_service (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, status_id INTEGER DEFAULT NULL, has_competent_authority_id INTEGER NOT NULL, identifier VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, processing_time VARCHAR(255) DEFAULT NULL --(DC2Type:dateinterval)
        , keyword VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO public_service (id, status_id, has_competent_authority_id, identifier, name, description, processing_time, keyword) SELECT id, status_id, has_competent_authority_id, identifier, name, description, processing_time, keyword FROM __temp__public_service');
        $this->addSql('DROP TABLE __temp__public_service');
        $this->addSql('CREATE INDEX IDX_BA43C5606BF700BD ON public_service (status_id)');
        $this->addSql('CREATE INDEX IDX_BA43C560F853E8FE ON public_service (has_competent_authority_id)');
        $this->addSql('DROP INDEX IDX_4BC417DA77CE3D8B');
        $this->addSql('DROP INDEX IDX_4BC417DA72F5A1AA');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_channel AS SELECT public_service_id, channel_id FROM public_service_channel');
        $this->addSql('DROP TABLE public_service_channel');
        $this->addSql('CREATE TABLE public_service_channel (public_service_id INTEGER NOT NULL, channel_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, channel_id))');
        $this->addSql('INSERT INTO public_service_channel (public_service_id, channel_id) SELECT public_service_id, channel_id FROM __temp__public_service_channel');
        $this->addSql('DROP TABLE __temp__public_service_channel');
        $this->addSql('CREATE INDEX IDX_4BC417DA77CE3D8B ON public_service_channel (public_service_id)');
        $this->addSql('CREATE INDEX IDX_4BC417DA72F5A1AA ON public_service_channel (channel_id)');
        $this->addSql('DROP INDEX IDX_8D0FA0C977CE3D8B');
        $this->addSql('DROP INDEX IDX_8D0FA0C9F909284E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_concept_isClassifiedBy AS SELECT public_service_id, concept_id FROM public_service_concept_isClassifiedBy');
        $this->addSql('DROP TABLE public_service_concept_isClassifiedBy');
        $this->addSql('CREATE TABLE public_service_concept_isClassifiedBy (public_service_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, concept_id))');
        $this->addSql('INSERT INTO public_service_concept_isClassifiedBy (public_service_id, concept_id) SELECT public_service_id, concept_id FROM __temp__public_service_concept_isClassifiedBy');
        $this->addSql('DROP TABLE __temp__public_service_concept_isClassifiedBy');
        $this->addSql('CREATE INDEX IDX_8D0FA0C977CE3D8B ON public_service_concept_isClassifiedBy (public_service_id)');
        $this->addSql('CREATE INDEX IDX_8D0FA0C9F909284E ON public_service_concept_isClassifiedBy (concept_id)');
        $this->addSql('DROP INDEX IDX_86EAC31D77CE3D8B');
        $this->addSql('DROP INDEX IDX_86EAC31DF909284E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_concept_sector AS SELECT public_service_id, concept_id FROM public_service_concept_sector');
        $this->addSql('DROP TABLE public_service_concept_sector');
        $this->addSql('CREATE TABLE public_service_concept_sector (public_service_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, concept_id))');
        $this->addSql('INSERT INTO public_service_concept_sector (public_service_id, concept_id) SELECT public_service_id, concept_id FROM __temp__public_service_concept_sector');
        $this->addSql('DROP TABLE __temp__public_service_concept_sector');
        $this->addSql('CREATE INDEX IDX_86EAC31D77CE3D8B ON public_service_concept_sector (public_service_id)');
        $this->addSql('CREATE INDEX IDX_86EAC31DF909284E ON public_service_concept_sector (concept_id)');
        $this->addSql('DROP INDEX IDX_9FE5FD2B77CE3D8B');
        $this->addSql('DROP INDEX IDX_9FE5FD2BF909284E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_concept_thematicArea AS SELECT public_service_id, concept_id FROM public_service_concept_thematicArea');
        $this->addSql('DROP TABLE public_service_concept_thematicArea');
        $this->addSql('CREATE TABLE public_service_concept_thematicArea (public_service_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, concept_id))');
        $this->addSql('INSERT INTO public_service_concept_thematicArea (public_service_id, concept_id) SELECT public_service_id, concept_id FROM __temp__public_service_concept_thematicArea');
        $this->addSql('DROP TABLE __temp__public_service_concept_thematicArea');
        $this->addSql('CREATE INDEX IDX_9FE5FD2B77CE3D8B ON public_service_concept_thematicArea (public_service_id)');
        $this->addSql('CREATE INDEX IDX_9FE5FD2BF909284E ON public_service_concept_thematicArea (concept_id)');
        $this->addSql('DROP INDEX IDX_F42D012E77CE3D8B');
        $this->addSql('DROP INDEX IDX_F42D012EF909284E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_concept_type AS SELECT public_service_id, concept_id FROM public_service_concept_type');
        $this->addSql('DROP TABLE public_service_concept_type');
        $this->addSql('CREATE TABLE public_service_concept_type (public_service_id INTEGER NOT NULL, concept_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, concept_id))');
        $this->addSql('INSERT INTO public_service_concept_type (public_service_id, concept_id) SELECT public_service_id, concept_id FROM __temp__public_service_concept_type');
        $this->addSql('DROP TABLE __temp__public_service_concept_type');
        $this->addSql('CREATE INDEX IDX_F42D012E77CE3D8B ON public_service_concept_type (public_service_id)');
        $this->addSql('CREATE INDEX IDX_F42D012EF909284E ON public_service_concept_type (concept_id)');
        $this->addSql('DROP INDEX IDX_4313688477CE3D8B');
        $this->addSql('DROP INDEX IDX_431368845A0D5235');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_contact_point AS SELECT public_service_id, contact_point_id FROM public_service_contact_point');
        $this->addSql('DROP TABLE public_service_contact_point');
        $this->addSql('CREATE TABLE public_service_contact_point (public_service_id INTEGER NOT NULL, contact_point_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, contact_point_id))');
        $this->addSql('INSERT INTO public_service_contact_point (public_service_id, contact_point_id) SELECT public_service_id, contact_point_id FROM __temp__public_service_contact_point');
        $this->addSql('DROP TABLE __temp__public_service_contact_point');
        $this->addSql('CREATE INDEX IDX_4313688477CE3D8B ON public_service_contact_point (public_service_id)');
        $this->addSql('CREATE INDEX IDX_431368845A0D5235 ON public_service_contact_point (contact_point_id)');
        $this->addSql('DROP INDEX IDX_F154F83577CE3D8B');
        $this->addSql('DROP INDEX IDX_F154F8351DBF857F');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_cost AS SELECT public_service_id, cost_id FROM public_service_cost');
        $this->addSql('DROP TABLE public_service_cost');
        $this->addSql('CREATE TABLE public_service_cost (public_service_id INTEGER NOT NULL, cost_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, cost_id))');
        $this->addSql('INSERT INTO public_service_cost (public_service_id, cost_id) SELECT public_service_id, cost_id FROM __temp__public_service_cost');
        $this->addSql('DROP TABLE __temp__public_service_cost');
        $this->addSql('CREATE INDEX IDX_F154F83577CE3D8B ON public_service_cost (public_service_id)');
        $this->addSql('CREATE INDEX IDX_F154F8351DBF857F ON public_service_cost (cost_id)');
        $this->addSql('DROP INDEX IDX_7C775E677CE3D8B');
        $this->addSql('DROP INDEX IDX_7C775E6D5F5D3E0');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_criterion_requirement AS SELECT public_service_id, criterion_requirement_id FROM public_service_criterion_requirement');
        $this->addSql('DROP TABLE public_service_criterion_requirement');
        $this->addSql('CREATE TABLE public_service_criterion_requirement (public_service_id INTEGER NOT NULL, criterion_requirement_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, criterion_requirement_id))');
        $this->addSql('INSERT INTO public_service_criterion_requirement (public_service_id, criterion_requirement_id) SELECT public_service_id, criterion_requirement_id FROM __temp__public_service_criterion_requirement');
        $this->addSql('DROP TABLE __temp__public_service_criterion_requirement');
        $this->addSql('CREATE INDEX IDX_7C775E677CE3D8B ON public_service_criterion_requirement (public_service_id)');
        $this->addSql('CREATE INDEX IDX_7C775E6D5F5D3E0 ON public_service_criterion_requirement (criterion_requirement_id)');
        $this->addSql('DROP INDEX IDX_5E9DD84D40C86FCE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_dataset AS SELECT id, publisher_id, identifier, name FROM public_service_dataset');
        $this->addSql('DROP TABLE public_service_dataset');
        $this->addSql('CREATE TABLE public_service_dataset (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, publisher_id INTEGER NOT NULL, identifier VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO public_service_dataset (id, publisher_id, identifier, name) SELECT id, publisher_id, identifier, name FROM __temp__public_service_dataset');
        $this->addSql('DROP TABLE __temp__public_service_dataset');
        $this->addSql('CREATE INDEX IDX_5E9DD84D40C86FCE ON public_service_dataset (publisher_id)');
        $this->addSql('DROP INDEX IDX_B4173894D95C7B13');
        $this->addSql('DROP INDEX IDX_B4173894C33F7837');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_dataset_document AS SELECT public_service_dataset_id, document_id FROM public_service_dataset_document');
        $this->addSql('DROP TABLE public_service_dataset_document');
        $this->addSql('CREATE TABLE public_service_dataset_document (public_service_dataset_id INTEGER NOT NULL, document_id INTEGER NOT NULL, PRIMARY KEY(public_service_dataset_id, document_id))');
        $this->addSql('INSERT INTO public_service_dataset_document (public_service_dataset_id, document_id) SELECT public_service_dataset_id, document_id FROM __temp__public_service_dataset_document');
        $this->addSql('DROP TABLE __temp__public_service_dataset_document');
        $this->addSql('CREATE INDEX IDX_B4173894D95C7B13 ON public_service_dataset_document (public_service_dataset_id)');
        $this->addSql('CREATE INDEX IDX_B4173894C33F7837 ON public_service_dataset_document (document_id)');
        $this->addSql('DROP INDEX IDX_D9FF02DF77CE3D8B');
        $this->addSql('DROP INDEX IDX_D9FF02DF71F7E88B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_event AS SELECT public_service_id, event_id FROM public_service_event');
        $this->addSql('DROP TABLE public_service_event');
        $this->addSql('CREATE TABLE public_service_event (public_service_id INTEGER NOT NULL, event_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, event_id))');
        $this->addSql('INSERT INTO public_service_event (public_service_id, event_id) SELECT public_service_id, event_id FROM __temp__public_service_event');
        $this->addSql('DROP TABLE __temp__public_service_event');
        $this->addSql('CREATE INDEX IDX_D9FF02DF77CE3D8B ON public_service_event (public_service_id)');
        $this->addSql('CREATE INDEX IDX_D9FF02DF71F7E88B ON public_service_event (event_id)');
        $this->addSql('DROP INDEX IDX_8236857077CE3D8B');
        $this->addSql('DROP INDEX IDX_82368570B528FC11');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_evidence AS SELECT public_service_id, evidence_id FROM public_service_evidence');
        $this->addSql('DROP TABLE public_service_evidence');
        $this->addSql('CREATE TABLE public_service_evidence (public_service_id INTEGER NOT NULL, evidence_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, evidence_id))');
        $this->addSql('INSERT INTO public_service_evidence (public_service_id, evidence_id) SELECT public_service_id, evidence_id FROM __temp__public_service_evidence');
        $this->addSql('DROP TABLE __temp__public_service_evidence');
        $this->addSql('CREATE INDEX IDX_8236857077CE3D8B ON public_service_evidence (public_service_id)');
        $this->addSql('CREATE INDEX IDX_82368570B528FC11 ON public_service_evidence (evidence_id)');
        $this->addSql('DROP INDEX IDX_50ECA12577CE3D8B');
        $this->addSql('DROP INDEX IDX_50ECA1259CF430C4');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_legal_resource AS SELECT public_service_id, legal_resource_id FROM public_service_legal_resource');
        $this->addSql('DROP TABLE public_service_legal_resource');
        $this->addSql('CREATE TABLE public_service_legal_resource (public_service_id INTEGER NOT NULL, legal_resource_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, legal_resource_id))');
        $this->addSql('INSERT INTO public_service_legal_resource (public_service_id, legal_resource_id) SELECT public_service_id, legal_resource_id FROM __temp__public_service_legal_resource');
        $this->addSql('DROP TABLE __temp__public_service_legal_resource');
        $this->addSql('CREATE INDEX IDX_50ECA12577CE3D8B ON public_service_legal_resource (public_service_id)');
        $this->addSql('CREATE INDEX IDX_50ECA1259CF430C4 ON public_service_legal_resource (legal_resource_id)');
        $this->addSql('DROP INDEX IDX_DE12565F77CE3D8B');
        $this->addSql('DROP INDEX IDX_DE12565F94C75C67');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_linguistic_system AS SELECT public_service_id, linguistic_system_id FROM public_service_linguistic_system');
        $this->addSql('DROP TABLE public_service_linguistic_system');
        $this->addSql('CREATE TABLE public_service_linguistic_system (public_service_id INTEGER NOT NULL, linguistic_system_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, linguistic_system_id))');
        $this->addSql('INSERT INTO public_service_linguistic_system (public_service_id, linguistic_system_id) SELECT public_service_id, linguistic_system_id FROM __temp__public_service_linguistic_system');
        $this->addSql('DROP TABLE __temp__public_service_linguistic_system');
        $this->addSql('CREATE INDEX IDX_DE12565F77CE3D8B ON public_service_linguistic_system (public_service_id)');
        $this->addSql('CREATE INDEX IDX_DE12565F94C75C67 ON public_service_linguistic_system (linguistic_system_id)');
        $this->addSql('DROP INDEX IDX_D0C95BAB77CE3D8B');
        $this->addSql('DROP INDEX IDX_D0C95BAB64D218E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_location AS SELECT public_service_id, location_id FROM public_service_location');
        $this->addSql('DROP TABLE public_service_location');
        $this->addSql('CREATE TABLE public_service_location (public_service_id INTEGER NOT NULL, location_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, location_id))');
        $this->addSql('INSERT INTO public_service_location (public_service_id, location_id) SELECT public_service_id, location_id FROM __temp__public_service_location');
        $this->addSql('DROP TABLE __temp__public_service_location');
        $this->addSql('CREATE INDEX IDX_D0C95BAB77CE3D8B ON public_service_location (public_service_id)');
        $this->addSql('CREATE INDEX IDX_D0C95BAB64D218E ON public_service_location (location_id)');
        $this->addSql('DROP INDEX IDX_92E2BC9877CE3D8B');
        $this->addSql('DROP INDEX IDX_92E2BC98DE097880');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_output AS SELECT public_service_id, output_id FROM public_service_output');
        $this->addSql('DROP TABLE public_service_output');
        $this->addSql('CREATE TABLE public_service_output (public_service_id INTEGER NOT NULL, output_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, output_id))');
        $this->addSql('INSERT INTO public_service_output (public_service_id, output_id) SELECT public_service_id, output_id FROM __temp__public_service_output');
        $this->addSql('DROP TABLE __temp__public_service_output');
        $this->addSql('CREATE INDEX IDX_92E2BC9877CE3D8B ON public_service_output (public_service_id)');
        $this->addSql('CREATE INDEX IDX_92E2BC98DE097880 ON public_service_output (output_id)');
        $this->addSql('DROP INDEX IDX_72C969E077CE3D8B');
        $this->addSql('DROP INDEX IDX_72C969E06ACE3B73');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_participation AS SELECT public_service_id, participation_id FROM public_service_participation');
        $this->addSql('DROP TABLE public_service_participation');
        $this->addSql('CREATE TABLE public_service_participation (public_service_id INTEGER NOT NULL, participation_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, participation_id))');
        $this->addSql('INSERT INTO public_service_participation (public_service_id, participation_id) SELECT public_service_id, participation_id FROM __temp__public_service_participation');
        $this->addSql('DROP TABLE __temp__public_service_participation');
        $this->addSql('CREATE INDEX IDX_72C969E077CE3D8B ON public_service_participation (public_service_id)');
        $this->addSql('CREATE INDEX IDX_72C969E06ACE3B73 ON public_service_participation (participation_id)');
        $this->addSql('DROP INDEX IDX_76885D5377CE3D8B');
        $this->addSql('DROP INDEX IDX_76885D53D95C7B13');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_public_service_dataset AS SELECT public_service_id, public_service_dataset_id FROM public_service_public_service_dataset');
        $this->addSql('DROP TABLE public_service_public_service_dataset');
        $this->addSql('CREATE TABLE public_service_public_service_dataset (public_service_id INTEGER NOT NULL, public_service_dataset_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, public_service_dataset_id))');
        $this->addSql('INSERT INTO public_service_public_service_dataset (public_service_id, public_service_dataset_id) SELECT public_service_id, public_service_dataset_id FROM __temp__public_service_public_service_dataset');
        $this->addSql('DROP TABLE __temp__public_service_public_service_dataset');
        $this->addSql('CREATE INDEX IDX_76885D5377CE3D8B ON public_service_public_service_dataset (public_service_id)');
        $this->addSql('CREATE INDEX IDX_76885D53D95C7B13 ON public_service_public_service_dataset (public_service_dataset_id)');
        $this->addSql('DROP INDEX IDX_A17F6C131B6D775');
        $this->addSql('DROP INDEX IDX_A17F6C13185387FA');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_public_service_related AS SELECT public_service_source, public_service_target FROM public_service_public_service_related');
        $this->addSql('DROP TABLE public_service_public_service_related');
        $this->addSql('CREATE TABLE public_service_public_service_related (public_service_source INTEGER NOT NULL, public_service_target INTEGER NOT NULL, PRIMARY KEY(public_service_source, public_service_target))');
        $this->addSql('INSERT INTO public_service_public_service_related (public_service_source, public_service_target) SELECT public_service_source, public_service_target FROM __temp__public_service_public_service_related');
        $this->addSql('DROP TABLE __temp__public_service_public_service_related');
        $this->addSql('CREATE INDEX IDX_A17F6C131B6D775 ON public_service_public_service_related (public_service_source)');
        $this->addSql('CREATE INDEX IDX_A17F6C13185387FA ON public_service_public_service_related (public_service_target)');
        $this->addSql('DROP INDEX IDX_1738DA481B6D775');
        $this->addSql('DROP INDEX IDX_1738DA48185387FA');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_public_service_requires AS SELECT public_service_source, public_service_target FROM public_service_public_service_requires');
        $this->addSql('DROP TABLE public_service_public_service_requires');
        $this->addSql('CREATE TABLE public_service_public_service_requires (public_service_source INTEGER NOT NULL, public_service_target INTEGER NOT NULL, PRIMARY KEY(public_service_source, public_service_target))');
        $this->addSql('INSERT INTO public_service_public_service_requires (public_service_source, public_service_target) SELECT public_service_source, public_service_target FROM __temp__public_service_public_service_requires');
        $this->addSql('DROP TABLE __temp__public_service_public_service_requires');
        $this->addSql('CREATE INDEX IDX_1738DA481B6D775 ON public_service_public_service_requires (public_service_source)');
        $this->addSql('CREATE INDEX IDX_1738DA48185387FA ON public_service_public_service_requires (public_service_target)');
        $this->addSql('DROP INDEX IDX_AFAAC00577CE3D8B');
        $this->addSql('DROP INDEX IDX_AFAAC005744E0351');
        $this->addSql('CREATE TEMPORARY TABLE __temp__public_service_rule AS SELECT public_service_id, rule_id FROM public_service_rule');
        $this->addSql('DROP TABLE public_service_rule');
        $this->addSql('CREATE TABLE public_service_rule (public_service_id INTEGER NOT NULL, rule_id INTEGER NOT NULL, PRIMARY KEY(public_service_id, rule_id))');
        $this->addSql('INSERT INTO public_service_rule (public_service_id, rule_id) SELECT public_service_id, rule_id FROM __temp__public_service_rule');
        $this->addSql('DROP TABLE __temp__public_service_rule');
        $this->addSql('CREATE INDEX IDX_AFAAC00577CE3D8B ON public_service_rule (public_service_id)');
        $this->addSql('CREATE INDEX IDX_AFAAC005744E0351 ON public_service_rule (rule_id)');
        $this->addSql('DROP INDEX IDX_43F32976744E0351');
        $this->addSql('DROP INDEX IDX_43F329769CF430C4');
        $this->addSql('CREATE TEMPORARY TABLE __temp__rule_legal_resource AS SELECT rule_id, legal_resource_id FROM rule_legal_resource');
        $this->addSql('DROP TABLE rule_legal_resource');
        $this->addSql('CREATE TABLE rule_legal_resource (rule_id INTEGER NOT NULL, legal_resource_id INTEGER NOT NULL, PRIMARY KEY(rule_id, legal_resource_id))');
        $this->addSql('INSERT INTO rule_legal_resource (rule_id, legal_resource_id) SELECT rule_id, legal_resource_id FROM __temp__rule_legal_resource');
        $this->addSql('DROP TABLE __temp__rule_legal_resource');
        $this->addSql('CREATE INDEX IDX_43F32976744E0351 ON rule_legal_resource (rule_id)');
        $this->addSql('CREATE INDEX IDX_43F329769CF430C4 ON rule_legal_resource (legal_resource_id)');
        $this->addSql('DROP INDEX IDX_CEBAD913744E0351');
        $this->addSql('DROP INDEX IDX_CEBAD91394C75C67');
        $this->addSql('CREATE TEMPORARY TABLE __temp__rule_linguistic_system AS SELECT rule_id, linguistic_system_id FROM rule_linguistic_system');
        $this->addSql('DROP TABLE rule_linguistic_system');
        $this->addSql('CREATE TABLE rule_linguistic_system (rule_id INTEGER NOT NULL, linguistic_system_id INTEGER NOT NULL, PRIMARY KEY(rule_id, linguistic_system_id))');
        $this->addSql('INSERT INTO rule_linguistic_system (rule_id, linguistic_system_id) SELECT rule_id, linguistic_system_id FROM __temp__rule_linguistic_system');
        $this->addSql('DROP TABLE __temp__rule_linguistic_system');
        $this->addSql('CREATE INDEX IDX_CEBAD913744E0351 ON rule_linguistic_system (rule_id)');
        $this->addSql('CREATE INDEX IDX_CEBAD91394C75C67 ON rule_linguistic_system (linguistic_system_id)');
    }
}
