# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # SET PRIORITIES FOR PublicService
    # -1 to not use custom data provider
    'App\DataProvider\PublicServiceCollectionDataProvider':
        tags: [ { name: 'api_platform.collection_data_provider', priority: -1 } ] #Switch -1:disconnect uom sparql, 1:connect uom sparql
        # Autoconfiguration must be disabled to set a custom priority
        autoconfigure: false

    # SET PRIORITIES FOR PublicOrganisation
    'App\DataProvider\PublicOrganisationCollectionDataProvider':
        tags: [ { name: 'api_platform.collection_data_provider', priority: -1 } ] #Switch -1:disconnect uom sparql, 1:connect uom sparql
        # Autoconfiguration must be disabled to set a custom priority
        autoconfigure: false

    
    
